### ISSUE TITLE
Disabling contextual LOB creation as createClob() method threw error running on Linux with PostgreSQL db 

### ISSUE THREAD

**Issue by vivanov19** [zalando/zally#1006]
Hello,

We are moving from the local Windows installation to the pre-prod one running on RedHat Linux entirely with our additional custom rules. 
The local Windows installation consists of the server (gradlew.bat) and web-ui image (with modified Docker file as suggested in one of the previous tickets) and run on in-memory HSQL db.
I've installed all pre-requisites including Docker and Yarn, etc., and somewhat successfully run ./build-and-run.sh shell script. 

It has created three images for me as follows:
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                              NAMES
8742dcad1e52        zally_web-ui        "node server.js"         3 hours ago         Up About a minute               0.0.0.0:8080->3000/tcp             zally_web-ui_1
2a66aceb57ad        zally_server        "/bin/sh -c 'java ..."   3 hours ago         Up About a minute (unhealthy)   0.0.0.0:8000->8000/tcp, 8080/tcp   zally_server_1
75cf0f15310a        postgres:9.6        "docker-entrypoint..."   3 hours ago         Up About a minute               0.0.0.0:54321->5432/tcp            zally_postgres_1

where postgres:9.6 image is the one to be run in production. 

When the server was starting it brought the following exception:
.................................................................................................................
server_1    | 2019-06-18 15:19:11.635  INFO 11 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.3.5.Final}
server_1    | 2019-06-18 15:19:11.637  INFO 11 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
server_1    | 2019-06-18 15:19:11.824  INFO 11 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
server_1    | 2019-06-18 15:19:12.213  INFO 11 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect
server_1    | 2019-06-18 15:19:12.481  INFO 11 --- [           main] o.h.e.j.e.i.LobCreatorBuilderImpl        : HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
server_1    | java.lang.reflect.InvocationTargetException: null
server_1    |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
server_1    |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
server_1    |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
server_1    |   at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
server_1    |   at org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl.useContextualLobCreation(LobCreatorBuilderImpl.java:113) [hibernate-core-5.3.5.Final.jar!/:5.3.5.Final]
.................................................................................................................
server_1    |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[zally.jar:na]
server_1    |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[zally.jar:na]
server_1    |   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[zally.jar:na]
server_1    | Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
server_1    |   at org.postgresql.Driver.notImplemented(Driver.java:688) ~[postgresql-42.2.4.jar!/:42.2.4]
server_1    |   at org.postgresql.jdbc.PgConnection.createClob(PgConnection.java:1269) ~[postgresql-42.2.4.jar!/:42.2.4]
server_1    |   ... 52 common frames omitted

it looks like it is Hibernate issue and the quick search recommends to set this flag to 'true':
(https://github.com/spring-projects/spring-boot/issues/12007)

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

but I am not sure how to do this. The stack trace above says that Hibernate Properties not found.

The rest of the framework works perfect. I can see active rules as the linter service on port 8000. The whole home page works (on port 8080) with all links except it fails, obviously, on the rules validation.

Are there are any suggestion how fix PostgreSQL or just switch back to HSQL in-memory db?

Any help will be highly appreciated.

Thank you,
Vladimir Ivanov

**Comment by roxspring** [comment]
Looks like the relevant Hibernate change (https://github.com/hibernate/hibernate-orm/commit/a5138621a69febf4f9ce9bd305a2f88775e4c5ae) went into versions 5.4.0+. I'm wary of upgrading Hibernate out-of-sync with Spring Boot which didn't adopt that version until 2.2.0.M2 + (https://github.com/spring-projects/spring-boot/commit/8efddf57a5394bc39aada380590edf0e6eb9c29c) and still isn't in an official release yet. I figure that upgrading to this once released will be the ideal fix.

In the meantime, the following change appears to achieve the config that @vivanov19 spotted and disable the "wall of text":

```
index 3226ace3..8f31a91a 100644
--- a/server/src/main/resources/application.yml
+++ b/server/src/main/resources/application.yml
@@ -8,6 +8,11 @@ spring:
   jpa:
     hibernate:
       ddl-auto: validate
+    properties:
+      hibernate:
+        jdbc:
+          lob:
+            non_contextual_creation: true
   oauth2:
     resource:
       tokenInfoUri: ${TOKEN_INFO_URI}
```

The effect of the config change can be seen in https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/LobCreatorBuilder.java#L63 and appears to just short circuit the method returning false, which is the same result as if the exception were thrown and logged https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/engine/jdbc/internal/LobCreatorBuilder.java#L106.

Pull request to follow.

**Comment by vivanov19** [comment]
Thank you, the setting was successfully tested on both native Linux RedHat 7.4 and on Debian Linux running on Windows.

So, I believe the ticket can closed.
