### ISSUE TITLE
feat: correct rule 154

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#1009]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/508 introduces changes which are relevant to the Zally project.

**Comment by vadeg** [comment]
Need to add a check for header parameters.

**Comment by vadeg** [comment]
There is no need for check. OpenAPI spec has relaxed requirements for these properties
> When this is true, parameter values of type array or object generate separate parameters for each value of the array or key-value pair of the map. For other types of parameters this property has no effect. 

See [Parameter object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameter-object)  in the specification.
