### ISSUE TITLE
Zally CLI should finish successful in case of server errors (5xx, 4xx)

### ISSUE THREAD

**Issue by zeitlinger** [zalando/zally#1033]
User Story
As a developer
I want the Zally CLI to succeed on (internal) server errors.
So that the build pipeline can proceed successful in case of Zally problems.

Description
We had a Zally outage because we could not reach the token info endpoint for authorization. As result we returned 502 - Bad Gateway.

**Comment by tkrop** [comment]
Actually decided to throw different error codes in case of *server* (1), *client* (2), and *validation* (3) errors.
