### ISSUE TITLE
Add CLI switches to influence error codes

### ISSUE THREAD

**Issue by tkrop** [zalando/zally#1035]
To control Zally behavior in the build pipeline, a command line switch to enable/disable error reporting on different errors would be good. We could support switches for:

* server error (1)
* client error (2)
* must violations (3)
* should violations (4)
* may violations (5)
* hints (6)

The default would be to report on the first three as now.

**Comment by vadeg** [comment]
Why we would need to disable server errors and client errors? What should Zally report in this case?

**Comment by vadeg** [comment]
The same as #653
