### ISSUE TITLE
Getting error while running the app on local environment

### ISSUE THREAD

**Issue by harpreet86** [zalando/zally#1044]
I have setup the application on local environment .
I have started the server process.
While running the web-ui application using "yarn start NODE_ENV=production", getting the error in browser cosole, please refer the attached screenshot:

![image](https://user-images.githubusercontent.com/4299180/64164214-664cc400-ce60-11e9-88c2-aae8cfb4b9e0.png)

**Comment by vadeg** [comment]
Hi @harpreet86,

Could you please provide some context:

* Which browser are you using?
* Could you provide some steps how to reproduce the error?

Thank you.

**Comment by harpreet86** [comment]
I am using node v10.15.3 and browser is chrome.

The interesting part is when I run using "sh build-and-run.sh", everything works fine.

But when I try to start web-ui using steps mentioned in readme, then access http://localhost:3000. It gives me the above error(attached in the screenshot).

**Comment by vadeg** [comment]
@harpreet86 this is an old ticket :) Sorry for a big delay. I was not able to reproduce the problem right now. Probably, some things have changed during the almost 3 years and the problem doesn't exist anymore. If you have time and still interested in the ticket feel free to reopen the ticket with additional data, e.g. commands you use, environment description, etc.
