### ISSUE TITLE
Customer_id example conflicts with backward compatibility constraints

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#1050]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/540 introduces changes which are relevant to the Zally project.

**Comment by vadeg** [comment]
Add `created_at` and `updated_at` to configuration. The format and type is the same as for `created` and `updated.

**Comment by tkrop** [comment]
Definitely not relevant for Zally.
