### ISSUE TITLE
Adding rule to check for the inclusion of Required & optional fields

### ISSUE THREAD

**Issue by JamesMurray031** [zalando/zally#1061]
Would there be any appetite to add a rule that checks for the inclusion of required and optional fields in your API?

**Comment by roxspring** [comment]
Are you suggesting a rule to enforce explicit `required: true` or `required: false` on parameters,  rather than letting it default to false? Seems reasonable to me.

**Comment by JamesMurray031** [comment]
That's the idea :)

**Comment by roxspring** [comment]
I'd expect that a PR adding this rule to the ZallyRuleSet would be accepted.

**Comment by vadeg** [comment]
Why it should be enforced? I guess it is clear for specification that `required` is by default `false`. Also `required` field have a different meaning depending on requires and response object.

**Comment by vadeg** [comment]
I think we can add [the following check](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields-10)
> If the parameter location is "path", this property is REQUIRED and its value MUST be true

**Comment by vadeg** [comment]
Solved via #1252.
