### ISSUE TITLE
mention alternatives to zally

### ISSUE THREAD

**Issue by zeitlinger** [zalando/zally#1070]

**Comment by zeitlinger** [comment]
For https://github.com/zalando/restful-api-guidelines/issues/544

**Comment by zeitlinger** [comment]
@whiskeysierra do you think we should mention https://nordicapis.com/8-openapi-linters/ as well?

**Comment by whiskeysierra** [comment]
Sure, doesn't hurt.

**Comment by zeitlinger** [comment]
@whiskeysierra better?
