### ISSUE TITLE
docker-compose Zally web UI not rendering

### ISSUE THREAD

**Issue by mckibbenc** [zalando/zally#1075]
When running docker-compose on Mac OS, the web-ui will not render.  The Zally API server works just fine, and I'm able to get the active rules and lint my APIs.  There are no build errors when running docker-compose, and I don't see any errors in the web-ui logs

docker container ls>
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS                              NAMES
f23c0a377db0        zally_web-ui        "node server.js"         3 minutes ago       Up 3 minutes               0.0.0.0:8080->3000/tcp             zally_web-ui_1
4462b742b339        zally_server        "/bin/sh -c 'java $(…"   3 minutes ago       Up 3 minutes (unhealthy)   0.0.0.0:8000->8000/tcp, 8080/tcp   zally_server_1
55d8f4af4219        postgres:9.6        "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes               0.0.0.0:54321->5432/tcp            zally_postgres_1

docker logs zally_web-ui_1>
zally-web-ui mounted on "/"
zally-web-ui running at http://localhost:3000

**Comment by mckibbenc** [comment]
I may have isolated this issue.  I modified the web UI Dockerfile to use the latest version of Node.js (version 13) and rebuilt the image.  Now the web UI renders properly.  My guess is the current version of node being referenced in the web ui Dockerfile (registry.opensource.zalan.do/stups/node:10.15.3-45) can't properly support the latest changes to the web ui, maybe due to outdated packages.  Here is the Dockerfile I used to build the working web ui image:

FROM node

MAINTAINER "http://zalando.github.io/"

COPY package.json ./
COPY yarn.lock ./

RUN npm install -g yarn
RUN yarn --production

COPY src ./src
COPY server.js ./

EXPOSE 3000

CMD ["node", "server.js"]


I would create a PR for this, but my guess is you guys will want to vendor your own updated node image instead of pulling from Docker hub.

**Comment by mckibbenc** [comment]
So it may not have to do with the node version.  I did a fresh clone on my Mac with the new node version, ran ./build-and-run.sh and then the docker-compose up, and it was still the same issue.  I could only get it to work if I manually built the web-ui by running npm install and yarn build within the web-ui directory.  ./build-and-run.sh fails on my Mac because of a :dokka issue.  I'm going to close this comment as it's probably user error on my end.

**Comment by dfrechette** [comment]
I'm having an issue with dokka also.

<pre>
...
Generating pages...

> Task :dokka FAILED
:dokka (Thread[Daemon worker Thread 2,5,main]) completed. Took 12.638 secs.

FAILURE: Build failed with an exception.
...
</pre>

**Comment by roxspring** [comment]
Well you’ve stopped the output just before it got interesting, but Shooting from the hip... try downgrading to Java 8 - Dokka doesn’t support javadoc format under newer java and blows up.

**Comment by sasisalt** [comment]
The latest version didn't solve the issue with web UI not rendering.
