### ISSUE TITLE
Support for RAML format

### ISSUE THREAD

**Issue by harpreet86** [zalando/zally#1095]
Does zally provide support to validate RAML input using **/api-violations**?

**Comment by roxspring** [comment]
No, Zally is focused on Swagger and OpenAPI format specs. It's a shame - I preferred RAML when first looking into REST API definitions - but from what I recall the models are quite different and I suspect we'd have to reimplement each rule to cope with the new format. And that's assuming there are appropriate RAML parsing libraries out there.

**Comment by harpreet86** [comment]
Thanks for the quick reply. I agree the support should be inbuilt otherwise I have to convert it to OAS format using some external converter before validation.

**Comment by tkrop** [comment]
@harpreet86 RAML is not part of Zalandos tech stack. As outside contribution seems to be very unlikely, I close this issue.
