### ISSUE TITLE
Update Flow-ID rule

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#1100]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/553 introduces changes which are relevant to the Zally project.

**Comment by vadeg** [comment]
Need to decide if the rule is needed in Zally. This would require for all APIs to define the header.

**Comment by vadeg** [comment]
Agreed not to implement this rule, because the `Flow-ID` header will be eventually replaced with [trace-id](https://www.w3.org/TR/trace-context/#trace-id) header.
