### ISSUE TITLE
Substitute Warning by Deprecation header

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#1105]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/556 introduces changes which are relevant to the Zally project.

**Comment by vadeg** [comment]
I don't think any updates in Zally are required, because as far as I remember it not required to define a `Deprecation` header in API definition ([Rule 189](https://opensource.zalando.com/restful-api-guidelines/#189)). @tkrop what do you think?

**Comment by tkrop** [comment]
@vadeg yes, I agree. In addition, we still have no rule checking for deprecated features, that checks for the headers.
