### ISSUE TITLE
Recently started facing one issue while running build-and-run.sh or running server jar

### ISSUE THREAD

**Issue by harpreet86** [zalando/zally#1121]
Please find below logs and suggest

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiViolationsController' defined in URL [jar:file:server/build/libs/zally.jar!/BOOT-INF/classes!/de/zalando/zally/apireview/ApiViolationsController.class]: Unsatisfied dependency expressed through constructor parameter 0; 
`

**Comment by roxspring** [comment]
Could this be the same as fixed yesterday in #1120? (caused by https://rawgit.com reaching end of life)

**Comment by harpreet86** [comment]
It worked for me after replacing the url in rules-config.conf `https://cdn.rawgit.com/googleapis/gnostic/master/OpenAPIv3/openapi-3.0.json` with `https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v3.0/schema.json`

Please suggest if this is the right approach.

**Comment by roxspring** [comment]
Yes, this should be a viable workaround if you can't move to a more recent build.
