### ISSUE TITLE
Official docker builds

### ISSUE THREAD

**Issue by dmarkey** [zalando/zally#1122]
Can we get official docker builds? There are many out of date/unofficial docker builds on docker hub that do not have the fix that recently went in. An official build would be very helpful.

**Comment by roxspring** [comment]
#761 tracks publishing official docker images. I had another go at it recently but it really needs one of the core Zalando folks to step up. It's a shame there's no jitpack.io for docker images!

Good to know that there are build on docker hub and people are trying to use them though.
