### ISSUE TITLE
Zally startup fails because https://rawgit.com reaching end of life and http://openapis.org/v3/schema.json is also a dead link

### ISSUE THREAD

**Issue by jmkhael** [zalando/zally#1129]
The issue also appears in https://github.com/zalando/zally/issues/1121
but https://github.com/zalando/zally/pull/1120 does not fix it as http://openapis.org/v3/schema.json is also a dead link.
however, replacing the url in rules-config.conf 
https://cdn.rawgit.com/googleapis/gnostic/master/OpenAPIv3/openapi-3.0.json with https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v3.0/schema.json works.

Thoughts?

**Comment by roxspring** [comment]
I was never particularly happy with #1120, it was just a quick fix to the symptom rather than addressing the underlying problems. #1126 aimed to properly address the (various) problems though, particularly defaulting to built-in copies of schemas rather than reaching out to the internet on startup. 

So the latest master version should avoid the problems you're seeing, and if not then please let us know why not! If you can't upgrade then, as discussed in #1121, replacing rawgit.com with githubusercontent.com links is a viable workaround.

**Comment by tkrop** [comment]
@roxspring actually, #1126. seems to have broken something for us too. I rolled back, but I didn't have the time to investigate since than.

**Comment by roxspring** [comment]
Oh? Any symptoms you can describe or stack traces to share? I've not seen any problems locally.

**Comment by tkrop** [comment]
Actually, no. Investigations showed nothing conserved in our logs. I will do a test in the next days. No urgent need to fix this currently.

**Comment by jmkhael** [comment]
The latest build does not resolve the issue du to also the fact that https://www.openapis.org/v3/schema.json is a dead link. The only viable solution is to apply the workaround for now until storing the schemas in the source.

**Comment by roxspring** [comment]
> The latest build does not resolve the issue du to also the fact that https://www.openapis.org/v3/schema.json is a dead link. The only viable solution is to apply the workaround for now until storing the schemas in the source.

I'm really puzzled by this 😕. The _only_ reference to https://www.openapis.org/v3/schema.json in the codebase is in setting up a redirection to a schema which _is_ stored in the source. Nothing should be attempting to resolve the link by default. The only time that URL should be resolved is if it's referenced directly in your `rules-config.conf`, or indirectly by whichever schema that references, in which case try removing them!

Does "The latest build" refer to a build from the latest master commit 490ab4c? If not, can you confirm which commit or where your build is coming from?

Can you confirm whether your `rules-config.conf` refers to any schema_urls? If so, can you share them?

**Comment by jmkhael** [comment]
Sadly I don't have the logs anymore. 

We had a `rules-config.conf` referencing the `cdn.rawgit` which I've changed. 
I don't have the startup errors anymore

I'll close this issue for now and reopen if faced again

thank you @roxspring
