### ISSUE TITLE
Invalid Docker Compose Healthcheck

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#1133]
The `docker-compose.yaml` defines a fairly reasonable health check based on the SpringBoot management endpoint, running on port 7979. The `MANAGEMENT_PORT` environment variable is also set to 7979, which `application.properties` uses to control the management port used by the server.

The `docker-compose.yaml` also defines `SPRING_PROFILES_ACTIVE=dev` making the server use `application-dev.properties`, which [hardcodes the management port to 8000](https://github.com/zalando/zally/blob/master/server/src/main/resources/application-dev.yml#L27). It's not clear to me why the dev profile should force a particular management port, but there were clearly many attempts to make that the case in the early days.

As a result, when running via the default docker-compose configuration, the health check can never succeed and so the server is always marked "unhealthy".

I'm very tempted to "fix" this by dropping all reference to the management port from the dev profile... if anybody can explain why this is a bad idea then please do so!

(Obviously, another "fix" option is to remove reference to health checks from the docker-compose configuration. This seems like a backwards step to me, but am open to persuasion.)

**Comment by vadeg** [comment]
I think it is fine to have management port `7979` in all cases. @tkrop do you know are there any specific reason why dev management port is `8080`?

**Comment by sirlatrom** [comment]
You can set `MANAGEMENT_SERVER_PORT` to override the property set in application-dev.properties.
