### ISSUE TITLE
ReverseAstBuilder parses incorrect JsonPointers for extensions

### ISSUE THREAD

**Issue by nikhilunni** [zalando/zally#1148]
For example, if there's a violation for:
```
info:
  x-example-extension: 4
```

This JsonPointer is parsed by the ReverseAstBuilder as: `/info/extensions/x-example-extension`, and so the line locator can't find the right node.

I'm working on a fix right now! I'll post a PR shortly.

**Comment by roxspring** [comment]
Haven't worked on the codebase in ages but am instantly sure you're right! Will keep a look out for the PR.
