### ISSUE TITLE
How to host Zally Linter as REST API 

### ISSUE THREAD

**Issue by SubratKumarGarnaik** [zalando/zally#1179]
We are planning to integrate API Linter into one of our review process pipeline to make it more efficient. But for that we need Zally API Linter hosted as an rest API. If you can help or guide me to host Zally API Linter as an rest API then it will serve our purpose.

**Comment by roxspring** [comment]
Have you read the README or any other docs? Have you tried anything yet? I think you're more likely to get a helpful response if you can demonstrate some progress and discuss a specific problem you've hit.

**Comment by SubratKumarGarnaik** [comment]
Yes. I do go through the README. Also set up the web-ui version and it is working fine. Now I am trying to explore the REST API version where I can integrate BitBucket with Zally API Linter. Please suggest on this regard.

**Comment by tkrop** [comment]
You can find the Zally server API a little bit hidden in https://github.com/zalando/zally/blob/master/server/zally-server/src/main/resources/api/zally-api.yaml. If you are running the zally server you can directly explore this API.
