### ISSUE TITLE
Usage of proprietary headers defined by Fashion Platform GW components

### ISSUE THREAD

**Issue by tfrauenstein** [zalando/zally#1181]
Guideline change with Zally rule impact -- check https://github.com/zalando/restful-api-guidelines/pull/598

We need whitelists for proprietary headers `x-zalando-client-id`, `x-zalando-request-host`, 
`x-zalando-request-uri`, `x-consumer`, `x-consumer-signature`, `x-consumer-key-id`

Whitelist must be sourced as Zally resource such that it can be easily extened via Zally PR

**Comment by ePaul** [comment]
Can be implemented analogously to #1173.
