### ISSUE TITLE
compileTestKotlin failure - ReviewStatistics cannot be resolved

### ISSUE THREAD

**Issue by Hez-Laine** [zalando/zally#1194]
I just cloned latest zally from master. And got compileKotlinTest failure as following:
e: /home/ehuahex/development/cross-ericsson-guild/zally/server/src/test/java/de/zalando/zally/apireview/RestApiBaseTest.kt: (8, 35): Unresolved reference: ReviewStatistics
e: /home/ehuahex/development/cross-ericsson-guild/zally/server/src/test/java/de/zalando/zally/apireview/RestApiBaseTest.kt: (34, 40): Unresolved reference: ApiReviewRepository

Could you please help me figure out why de.zalando.zally.statistic.ReviewStatistics cannot be resolved?

**Comment by tkrop** [comment]
@Hez-Laine Sorry, for the late reply. I cannot reproduce your error. You have to give much more information about your development environment and your executed commands, if you want me to help you. Please feel free to reopen the issue, if you still need help and can provide more context.
