### ISSUE TITLE
Editorial updates around Standard Data Format rules

### ISSUE THREAD

**Issue by ePaul** [zalando/zally#1217]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/643 introduces changes which are relevant to the Zally project.

- [ ] Add support of 10 [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) formats.
- [ ] Generate configuration with allowed formats for the rule from the list
- [ ]

**Comment by vadeg** [comment]
Implement a rule which checks data format or requests and responses.

**Comment by vadeg** [comment]
See PR comment.
