### ISSUE TITLE
Inherit from Zalando's rules

### ISSUE THREAD

**Issue by jeangael-domine** [zalando/zally#1219]
Hi,

I am currently starting to use Zally and I have a set of rules specific to my company (I forked the repo).
In this set some are duplicates of Zalando's ones except that the id of the rules in question is different.

Thus I'd like to inherit from the Zalando's rule and just overwrite the properties in the @Rule annotation? But all the rules are final and thus I cannot do that.

What do you think of opening them?

Thanks

**Comment by vadeg** [comment]
Hi @jeangael-domine !

Have you considered to use [delegation](https://kotlinlang.org/docs/delegation.html)?

**Comment by malika-lintillac** [comment]
Hi @vadeg !

Thanks for your answer!

To be honest, no I did not :)

But I have two questions about using this:

1. Doing so means that I should be providing an instance of the Zalando's rule to my own rule in the constructor. However all the rules are currently instantiated by a generic system (RulesManager if I'm not mistaken). So it means I would have to modify this to be able to provide the delegate.
And I'd like to avoid this as it would mean modifying the core module which in my opinion should remain untouched as much as possible

2. As the rules do not implement an interface, I cannot do a real Kotlin delegation (I mean using the **by** operator). I could still do it but it would not be as great, don't you think?

All in all, I think it is a good idea but I see some things that bother me.

**Comment by jeangael-domine** [comment]
Hi @vadeg !

Thanks for your answer!

To be honest, no I did not :)

But I have two questions about using this:

Doing so means that I should be providing an instance of the Zalando's rule to my own rule in the constructor. However all the rules are currently instantiated by a generic system (RulesManager if I'm not mistaken). So it means I would have to modify this to be able to provide the delegate.
And I'd like to avoid this as it would mean modifying the core module which in my opinion should remain untouched as much as possible

As the rules do not implement an interface, I cannot do a real Kotlin delegation (I mean using the by operator). I could still do it but it would not be as great, don't you think?

All in all, I think it is a good idea but I see some things that bother me.

**Comment by vadeg** [comment]
> Doing so means that I should be providing an instance of the Zalando's rule to my own rule in the constructor. 

Not exactly. I think delegation was not the correct example. You can create your rule and in the constructor initialize Zalando rule you need. It more like a wrapper rather than delegate.

> I could still do it but it would not be as great, don't you think?
Yes, agree. I think it would be easier to make rules open as you suggested. @tkrop what do you think?

**Comment by tkrop** [comment]
@vadeg Opening rules for inheritance may be possible as long as we have protect the implementation details of the opened rules. However, I would prefer to not support inheritance as long as instantiation of a rule in a `WrapperRule` is sufficiently easy. May be, we can integrate an `abstract WrapperRule` to support the necessary delegation mechanisms.

@jeangael-domine do you like to contribute?

**Comment by jeangael-domine** [comment]
Hi @tkrop 

Can you confirm that I got your idea right:
To add a `WrapperRule` class so that the Kotlin delegation can be used?
It means an evolution of the RulesManager process of all the rules to be capable of providing an instance of another rule, right?

However I have a comment. I thought that the refactoring you did to separate the code into modules gave the flexibility to not include the zalando ruleset in an app that does not need it (my case since I want to change the rules codes).
That is why I thought of inheritance because in that case, simply adding a dependency with my own ruleset should be enough (unless I'm wrong).
In the case of delegation, every Zalando rule would need to be instantiated and declared as ignored (to avoid having the same rule applied twice) in the configuration file.

Am I getting it right?

As for your question about a contribution, I'm not as good as you guys are I think but I could still give it a try

**Comment by vadeg** [comment]
Inheritance would not solve the problem of running Zalando rules. If you have Zalando ruleset in a classpath and will add your rule, which inherits from Zalando rule, you will have two rules running: one is the original Zalando rule and another one is the your's new rule. Rules are loaded using a similar approach as [ServiceLoader](https://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html): it will scan `/META-INF/services` of all jar in a classpath and will load all rules defined there. 

Inheritance would not solve this problem, but will introduce additional complexity of keeping public rules interface clean, consistent and keeping the mutable state inside. I would recommend to:
1. Use composition instead of inheritance.
2. Disable Zalando rule which you don't want to run.

**Comment by jeangael-domine** [comment]
OK my bad, I mistakingly thought that the ruleset would only be instantiated if I added it to the server dependencies.
Thanks for the explanation of the ServiceLoader, it makes things much more clearer to me.
I'll look into your proposal as soon as possible

**Comment by vadeg** [comment]
@jeangael-domine I will close the ticket at the momeng. Feel free to reopen if needed.
