### ISSUE TITLE
Maven plugin

### ISSUE THREAD

**Issue by baurchanu** [zalando/zally#1232]
Hi, thx for the great linter!

It would be useful for some cases to use Zally as a maven plugin. I can submit a PR, if you don't mind.

**Comment by vadeg** [comment]
Hi @baurchanu ,

Yes, sure. Good idea!

**Comment by baurchanu** [comment]
Hi, could someone review the PR, pls?

**Comment by vadeg** [comment]
We have decided not to add Zally maven plugin directly to Zally. Check [this PR comment](https://github.com/zalando/zally/pull/1300#issuecomment-898511367) for details.
