### ISSUE TITLE
Permalink in Zally UI is very slow that it appears somethimes broken.

### ISSUE THREAD

**Issue by tkrop** [zalando/zally#1235]
This issue a placeholder for an Zalando internal issue. Please have a look at [developer-console/issues#595](https://github.bus.zalan.do/pitchfork/developer-console/issues/595) for details.

**Comment by vadeg** [comment]
When open the permalink, the request `https://zally.zalando.net/zally-api/api-violations/<revision_id>` takes ~1 minute to execute. Need to investigate why. Also, there was an error
```
WARN 8 --- [nio-8080-exec-3] i.s.v.p.processors.ExternalRefProcessor  : A model for class ComposedSchema {
    class Schema {
...
} already exists
```

**Comment by vadeg** [comment]
The parser error is not related to the request, because there is no rule parsing happens during `GET /api-violations/<api_id>`.  Need more evidence what is the root cause of delays.
