### ISSUE TITLE
Editorial: highlight 'note' as an 'exception'

### ISSUE THREAD

**Issue by ePaul** [zalando/zally#1241]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/663 introduces changes which are relevant to the Zally project.

**Comment by tkrop** [comment]
@vadeg not sure whether we can add this exception formally somehow in https://github.com/zalando/zally/blob/32a9d6ed99c5b885afc6a85fc6ab73104c193959/server/zally-ruleset-zalando/src/main/kotlin/org/zalando/zally/ruleset/zalando/UpperCaseEnums.kt?

**Comment by vadeg** [comment]
I don't think we can. The number of exceptions is quite big and additional semantics would be required to distinguish `GB` as a country from `GB` as something else (e.g. data measurement unit).

**Comment by vadeg** [comment]
I am closing it. Feel free to reopen if needed.

**Comment by ePaul** [comment]
> I don't think we can. The number of exceptions is quite big and additional semantics would be required to distinguish `GB` as a country from `GB` as something else (e.g. data measurement unit).

Just a nit pick: Those would both be upper case anyways.

But I agree, getting a full allow-list is infeasible.
(One could likely include the language codes somehow (e.g. by checking whether there exists a Locale with this language), but I'm not sure that a solution which just covers this one example makes much sense.)
