### ISSUE TITLE
Replace `Open API` with `OpenAPI` everywhere -- missing replacements

### ISSUE THREAD

**Issue by ePaul** [zalando/zally#1243]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/664 introduces changes which are relevant to the Zally project.

**Comment by tkrop** [comment]
Nothing to do for Zally - except may be for doing a similar change of `Open API` to `OpenAPI` here two. However, the one location is in the OpenAPI-3 schema description we have copied from the source ...
