### ISSUE TITLE
Add "X-Zalando-Customer" to the Rule 183

### ISSUE THREAD

**Issue by vadeg** [zalando/zally#1272]
Add `X-Zalando-Customer` header in the allowed proprietary headers list for Rule 183

**Comment by vadeg** [comment]
Decided to add a header to the [allowed headers list](https://github.com/zalando/zally/blob/master/server/zally-ruleset-zalando/src/main/resources/reference.conf#L192).

**Comment by RhnSharma** [comment]
I would like to take this one.
