### ISSUE TITLE
Not able to run tool

### ISSUE THREAD

**Issue by harpreet86** [zalando/zally#1292]
Getting the exception as in below screenshot:

![image](https://user-images.githubusercontent.com/4299180/125255747-600bb680-e319-11eb-9a87-6e738a6e6d7f.png)

**Comment by vadeg** [comment]
Hi @harpreet86 
Could you give some details (Java version, command you run, OS)? 
Also, run with `--debug` or `--info` option to print the exact error.

**Comment by harpreet86** [comment]
Command: sh build-and-run.sh
OS: Windows 10
Java version on machine: Java 8

I am referring the quick start guide from https://github.com/zalando/zally

**Comment by vadeg** [comment]
Could you try with Java 11?

**Comment by harpreet86** [comment]
I am trying to run using shell script _build-and-run.sh_ which uses Docker and I can see that _Dockerfile_ of _server_ contains Java 11 `FROM registry.opensource.zalan.do/library/openjdk-11-jdk-slim:latest as builder`

**Comment by vadeg** [comment]
I confirm that there are some issues with this command.

**Comment by vadeg** [comment]
@harpreet86 try to increase the memory size in a Docker settings.

**Comment by harpreet86** [comment]
I tried it by skipping the test cases and the things worked well, so the issue seems with the unit test cases execution

**Comment by vadeg** [comment]
I don't think so. Please check my recommendation above.

**Comment by harpreet86** [comment]
I installed Java 11 on my windows machine and then tried and it worked. Now I am very curious that we are using containerized solution and the docker image has Java 11 then why it is relying on Windows machine Java version. Please suggest. 
Also, as per my observation, it runs successfully with Java 8 on my Windows machine just by skipping unit test cases in gradle command.

**Comment by harpreet86** [comment]
Any update. Please suggest.

**Comment by vadeg** [comment]
@harpreet86 could you please add here the result of the following command:
```
docker info | grep "Total Memory"
```

By default Docker has a 2Gb memory limit. I have tested the build and according to the statistics from Docker during the build it requires ~2,5 Gb of memory. When there is only two available, then linux daemon kills the gradle daemon as the biggest memory consumer at some point and the build process fails. I have tested with 3Gb memory limit for Docker and it works fine.

**Comment by beena-yatin-kanyal** [comment]
@vadeg  - I am facing the issue as well and running the code java8 breaks the test case due to the version mismatch error while skipping the test cases Gradle build works fine. Also sharing the information you requested -
![image](https://user-images.githubusercontent.com/46935197/136944450-7a201d67-9b9b-480d-be36-258182750176.png)

**Comment by vadeg** [comment]
@beena-yatin-kanyal zally doesn't support Java 1.8 any longer. The min version should be 11 and it is taken from the docker image and not from the host machine. 
It is simply to check to change the line `RUN ./gradlew build` in `server/Dockerfile` to `RUN java --version; ./gradlew build`. In this case you can see in logs which Java version is used to build the server.

**Comment by tkrop** [comment]
@harpreet86 @volphy @beena-yatin-kanyal are there still issues with the tools when setting up everything for Java 11? Should we update the documentation?

**Comment by vadeg** [comment]
I am closing this ticket. Feel free to reopen if there is still an issue.
