### ISSUE TITLE
Strict Spec validation yielding a weird error message

### ISSUE THREAD

**Issue by djjorjinho** [zalando/zally#1305]
I have a path specification with a response that contains a `description` and a `$ref` to a reusable response component.
Example: 

```yaml
# openapi 3.0.1
400:
  description: |
    Malformed data or
    ranks array includes multiple ranks entries for the same merchant
  $ref: '#/components/responses/GenericError'
```

Zally outputs a violation, but instead of stating that the response definition cannot contain `description` and a `$ref` in the same block (spec violation) it instead outputs this error:

```
Does not match openapi3 schema: Instance failed to match exactly one schema of: #/definitions/response; #/definitions/reference

Rule: https://zalando.github.io/restful-api-guidelines/#101

Location: paths > /offer-selections > post > responses > 400
```

Removing `description` fixed the issue; however, the error message seems a bit odd and unrelated to the spec inconsistency problem.

**Comment by vadeg** [comment]
I think it has been discussed already in #690. An error is provided by schema validator which checks that schema is valid in general and prevents to spawn false positive violations. The [response object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#responses-object) can have either `$ref` or response object defined inline. The error says exactly this.

**Comment by tkrop** [comment]
While this is a kind of misleading error message, it is also clearly stating where and what the error is. I suggest to close it, since adding a mindful wrapper for this error message seems unjustifiable complex.
