### ISSUE TITLE
Update the Custom Rule Creation documentation

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [zalando/zally#1337]
In the documentation available at this [link](https://github.com/zalando/zally/blob/master/documentation/rule-development.md), the imports listed at this are not available in the Zally code anymore. Please update the documentation so that readers can correctly understand and work to create better documentation as per the organization.

```
import de.zalando.zally.rule.api.Check
import de.zalando.zally.rule.api.Context
import de.zalando.zally.rule.api.Rule
import de.zalando.zally.rule.api.Severity
import de.zalando.zally.rule.api.Violation
```

Thanks.

**Comment by ePaul** [comment]
Those classes are now in package `org.zalando.zally.rule.api` (instead of `de.*`).

**Comment by beena-yatin-kanyal** [comment]
Thanks. closing this issue.

A recommendation is to please update the documentation.

**Comment by ePaul** [comment]
I'm reopening the issue for updating the documentation. (Feel free to open a PR.)
