### ISSUE TITLE
Editing the web-ui component pages

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [zalando/zally#1340]
hi, I am working on the zally web-ui to add some of the organization-specific customizations to the below page.

![image](https://user-images.githubusercontent.com/46935197/141501456-2c134162-e09e-4016-ba14-06161f1e82d9.png)

however even after changing the file and it is getting compiled successfully (application running the yarn dev mode) but still the customization is not getting reflected on the page. can anyone please tell me where to get this started? Below are the compilation logs for reference -

```
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Hash: 6ce003d644ef0f6a128b
Version: webpack 4.32.2
Time: 734ms
Built at: 11/12/2021 10:01:39 PM
    Asset     Size  Chunks             Chunk Names
bundle.js  6.9 MiB    main  [emitted]  main
Entrypoint main = bundle.js
[./src/client/app/components/violations.jsx] 4.42 KiB {main} [built]
    + 149 hidden modules
i ｢wdm｣: Compiled successfully.

```

**Comment by ePaul** [comment]
Hi Beena,

sorry for the late answer. Could you tell what exactly you've changed, and where you expect your changes to show up?

**Comment by beena-yatin-kanyal** [comment]
Hi @ePaul - I was managed to get this working by adding the below property in the `dev.js` file.

`writeToDisk: true // only add for development window. so that yarn can pick file changes.`

the purpose of this question was to find the property that will help to see the UI changes during development without rebuilding the web-ui each time. I think the UI development guide should have this information. Please feel free to close this issue.
