### ISSUE TITLE
Unable to run the application on local machine

### ISSUE THREAD

**Issue by harpreet86** [zalando/zally#1359]
Facing the issue below:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/4299180/153568877-a09387e5-d611-4c51-984a-cc80ddd7a40c.png">

Running the application using **./build-and-run.sh**

**Comment by dwi13L** [comment]
Can you elaborate on this, please?
I'm running v2.1.1 and I'm facing this issue while the app requires v18 or above
