### ISSUE TITLE
Mismatch in nodeVersion for Web-ui "Packages.json" and "Dockerfile"

### ISSUE THREAD

**Issue by ddkserv** [zalando/zally#1419]
Hi Zally Maintainers,

Please be advised that the web-ui has mismatch in nodeVersion for build and Dockerfile.

/web-ui/package.json ==> Requires nodeVersion 17.x or highere.

```JSON
  "engines": {
    "node": ">=17"
  },
```

/web-ui/Dockerfile ==> yarn --production will be executed on nodeVersion 14. 
```Dockerfile
FROM registry.opensource.zalan.do/library/node-14-alpine:latest

MAINTAINER "http://zalando.github.io/"

COPY package.json ./
COPY yarn.lock ./

RUN yarn --production
```

Thanks.

**Comment by defaude** [comment]
This is a more specific explantation of #1418 👍

**Comment by defaude** [comment]
I'm currently preparing a PR for this.

But for whatever reason, the gradle build takes _**FOREVER**_ on my machine. I assume it's not _really_ compatible with Apple Silicon? Might take a look into that one next ;)

**Comment by defaude** [comment]
See #1420 for the PR.

And to correct my previous comment regarding the gradle build taking long: That's not true ;) If I run the gradle build on my machine directly, it runs for about 2 minutes (including tests).

However, what's taking super long is trying to run the build with the given Dockerfile. I assume the base image is not "properly" compatible with Apple Silicon:

```
FROM registry.opensource.zalan.do/library/openjdk-11-jdk-slim:latest as builder
```

(and therefore runs in the crappy emulation)
