### ISSUE TITLE
Update Swagger-Parser Dependency to 2.1.12

### ISSUE THREAD

**Issue by jeffrey-ng** [zalando/zally#1445]
Zally's current version Swagger Parser (2.1.9) incorrectly throws exceptions with relative `$ref` within a spec.
Updating to 2.1.12 should fix the issue.

https://github.com/swagger-api/swagger-parser/issues/1865
https://github.com/swagger-api/swagger-parser/commit/138687c5385556a648ed2a14528f522670242f99

**Comment by tkrop** [comment]
Thank you very much for the information. Will update version as soon as possible.

**Comment by ktsypkina** [comment]
the Swagger Parser dependency was upgraded to 2.1.12 @jeffrey-ng
