### ISSUE TITLE
Consider setting @SupportedSourceVersion to SourceVersion.RELEASE_17

### ISSUE THREAD

**Issue by mkjensen** [zalando/zally#1449]
Since you are already preparing for Spring Boot 3 and Java 17 (https://github.com/zalando/zally/pull/1433), maybe you can also consider changing [`https://github.com/zalando/zally/blob/main/server/zally-core/src/main/kotlin/org/zalando/zally/core/RuleProcessor.kt`](https://github.com/zalando/zally/blob/aa5b0b2ebfd1eac95556e153d3f67ae341e49847/server/zally-core/src/main/kotlin/org/zalando/zally/core/RuleProcessor.kt#L14) from `@SupportedSourceVersion(SourceVersion.RELEASE_11)` to `@SupportedSourceVersion(SourceVersion.RELEASE_17)`.

Then we can avoid the following Maven warning in a Spring Boot 3 project:
```
[WARNING] Supported source version 'RELEASE_11' from annotation processor 'org.zalando.zally.core.RuleProcessor' less than -source '17'
```

Thanks.

**Comment by ePaul** [comment]
Could you open a pull request for this? Then it can fit into the next release.

Thanks!
