### ISSUE TITLE
Mark Rules in API Guidelines as "Automated with Zally"

### ISSUE THREAD

**Issue by netme** [zalando/zally#151]
In order to make our project more visible from outside, we can attract some traffic from the API Guidelines. 

Close to the rules which are already supported in Zally we can put a special label "Automated with Zally".

**Comment by maxim-tschumak** [comment]
We decided not to mark the rules as "Automatically Checked by Zally":
* The readers would rely on Zally and ignore reading the rule description and reasoning
* In many cases, not all aspects of the Rule are covered with checks
