### ISSUE TITLE
Refactor containers and http-client 

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#463]
Author: @rbarilani; Copied from the legacy Zally Web-UI repository.

**As a** developer
**I want** to have clearer containers structure
**So that** I can easily navigate in the project

**Description** Currently we have navigation part in violations container. I suggest to move it to separate container navigation so it will be logical.

**As a** developer
**I want** to have more powerful http client
**So that** I can send requests easier

**Description** We use aurelia-fetch-client it is HTTP client based on the Fetch API. It doesn't support query parameters. I suggest to switch to something more powerful so we don't need to write basic things ourselves. It can be aurelia-http-client

**Comment by topicus** [comment]
@maxim-tschumak The first one was address by @ruiaraujo here https://github.com/zalando-incubator/zally/commit/3dae661ccc7e6054cd1485d3f867291d9a708af0#diff-aadae5aaecb0ac146aeb3a41cf106dd9

Regarding the aurelia-fetch-client replacement, build query parameters it's not part of the fetch api standard but this problem could be easily solved using aurelia-path (see https://gist.github.com/bryanrsmith/14caed2015b9c54e70c3#gistcomment-1876949). Also, aurelia provides several features that are not present in other libraries. For example: interceptors. In other words, replacing aurelia-fetch-client could cause more problems that it solves.

**Comment by maxim-tschumak** [comment]
@rbarilani please have a look!

(@rbarilani is the original author of this issue; it was moved during the migration)

**Comment by rbarilani** [comment]
@maxim-tschumak I think they were two different stories, the first one was mine the other one If I am not mistaking was created by @Nagogus.

Regarding aurelia I agree with @topicus
