### ISSUE TITLE
[GHE Integration] Web UI

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#484]
**As a** user of Zally GHE Integration Solution
**I want** to have a web user interface
**So that** I am able to view detailed information about current and past API reviews

**Acceptance Criteria**
- PR comments include a link to the Zally GHE Integration Web UI
- Following the link, the user sees the detailed results of the API review
- User can also view historical API reviews and the detailed results

**Comment by vadeg** [comment]
This would be done by another component internal to Zalando. Current and past API reviews could a part of Zally UI.
