### ISSUE TITLE
Switch to Rule Ids defined in the Zalando RESTful API Guidelines 

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#497]
**As a** user of Zally and [Zalando RESTful API Guidelines](http://zalando.github.io/restful-api-guidelines/)
**I want** to have a proper linking between rule implementation (Zally) and specification (Guidelines)
**So that** there is consistency and referential integrity

**Acceptance Criteria**
* Rule IDs are in sync with [Zalando RESTful API Guidelines](http://zalando.github.io/restful-api-guidelines/)
* Links in rule descriptions and violations refer to the correct rule in the Guidelines
* Review statistics refer to the Guideline rules by the new id
* An overview of automated rules is created (simple mapping `RuleClassName` <-> `RuleId`)

Depends on https://github.com/zalando/restful-api-guidelines/issues/260 (already live).

**Comment by netme** [comment]
Checked the current Zally implementation. We need to find a bit better approach here: sometimes we have few Zally rules behind 1 guidelines rule. Good example is [Rule 104](http://zalando.github.io/restful-api-guidelines/#104), it's checked in Zally in M004, M010 and M017. 

I will still open a preparation pull request which will fix the URLs to REST API guidelines and add the `guidelineCode` parameter and later we'll try to find a good approach here.

**Comment by netme** [comment]
Also, some Zally rules don't have any REST API Guidelines rules behind. We need to find a good approach for that.

**Comment by maschleg** [comment]
I would say one api guideline rule is represented as one ally rule. Maybe there are some situations where it make sense to split the implementation in two rules for better readability. For your example I would say M004 is actually rule [#105](http://zalando.github.io/restful-api-guidelines/#105) and M010 and M017 can be merged.

**Comment by maxim-tschumak** [comment]
Hm.. What is the relation between zally rule implementation and guideline rules? Is it `1-to-n` or `n-to-m`?

**Comment by netme** [comment]
@maxim-tschumak , so far I've seen `1-to-n` only

**Comment by maxim-tschumak** [comment]
What do you think about going through the rules and try to merge them, so that the Zally rules are `1-to-1` to the guideline rules?

**Comment by netme** [comment]
Discussed with @maxim-tschumak . Concept should be defined first.

**Comment by roxspring** [comment]
FWIW we're starting to experiment with Zally and initially found the variety of ids to be a little confusing - especially seeing a violation and trying to trace back where the code was that raised it, or similarly revising a guideline and identifying relevant rules. Our planned solution to this will be to group rules into packages matching the guideline sections and using `.javaClass.simpleName` for the various ids.

**Comment by roxspring** [comment]
Think the first 3 points of the acceptance criteria are addressed by #559 work. Can you expand on what's needed for the 4th point @maxim-tschumak? (Mapping is just a build artefact? Available via web-ui? Committed with "source" markdown file?)

**Comment by maxim-tschumak** [comment]
@roxspring Somehow I failed to update this issue. `supported-rules` and the web view should be enough to cover the 4. point.
Closing..
