### ISSUE TITLE
New Check: API Title Must be Set

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#553]
**Description:** API Title in the OpenAPI definition must be set. This is related to [101](http://zalando.github.io/restful-api-guidelines/#101)

**Acceptance Criteria**
- New Zally check validates if `info.title` is set and is not empty (there is no minimal length)
- New check is implemented and tested

**Comment by vpondala** [comment]
Can I work on this one?

**Comment by maxim-tschumak** [comment]
Sure @vpondala !

**Comment by netme** [comment]
Taking it over
