### ISSUE TITLE
Permalinks to reviews

### ISSUE THREAD

**Issue by codekultur** [zalando/zally#593]
It would be great, if Zally could provide a permalink to a review. So I could send findings via mail, chat etc. . Currently I always have to explain to go to Zally and either paste the API definition in the editor or provide the Git Hub link. If I had a permalink, the receiver of the message could just go to Zally and see what I mean.

**Comment by netme** [comment]
Really great idea, we already talked a lot about it during GH Integration project and had some thoughts on how to automate it.

**Comment by ruiaraujo** [comment]
@netme We could do it stateless for URL based checks.

We just encode the url in the link.

**Comment by ruiaraujo** [comment]
The ui could handle that easily.

**Comment by vadeg** [comment]
I can suggest to use an `id` field from `ApiReview` class in permalink and add an endpoint like `GET /api-violations/<review-id>` which will return review results. In general, following steps should be done:
* Implement `/api-violations/<review-id>` endpoint which should return review results.
* Update `ApiDefinitionResponse` by adding `review-id` which can be used to build permalink in UI.

What do you think?

**Comment by vadeg** [comment]
> suggest we use a randomly assigned UUID for this purpose

Would be nice, but not necessary. Numeric value as a string and then can be safely replaced with uuid if needed. In this case no migration needed to already existing reviews.

**Comment by roxspring** [comment]
How do you expect existing reviews to be accessed? Users won't have the ids for them, numeric or uuid, and I've seen no requirement for listing reviews.

**Comment by vadeg** [comment]
Yeah, you're right. I forgot that there is no way to access it right now :).

**Comment by roxspring** [comment]
(whoops - misclick!)

**Comment by maxim-tschumak** [comment]
implemented in #901

**Comment by roxspring** [comment]
API was implemented but no UI.

Hope to open a UI pull request tomorrow.
