### ISSUE TITLE
HyphenateHttpHeadersRule implements non-existent rule 131

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#607]
[HyphenateHttpHeadersRule ](https://github.com/zalando-incubator/zally/blob/master/server/src/main/java/de/zalando/zally/rule/zalando/HyphenateHttpHeadersRule.kt) references a [guideline](https://zalando.github.io/restful-api-guidelines/#131) which doesn't exist.

Unless somebody is busy writing up the guideline then I imagine we should be deleting the rule.

**Comment by maxim-tschumak** [comment]
Good catch! Let's move this rule to the Zally Rule Set ;)

**Comment by roxspring** [comment]
Sounds reasonable. Will probably wait for #606 before making further changes though.
