### ISSUE TITLE
OAuth2.0 Integration for Web UI

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#631]
**Background information:**
Currently, we @ zalando have a "zally-web-ui appliance" project. It is mainly used to integrate OAuth2.0 by implementing OAuth flow on top of `@zalando/zally-web-ui` package. The result is deployed within the Zalando organization.
If I remember correctly, we initially decided to split up these projects to hide internal details about Zalando's infrastructure. But there is probably a way to make it configurable ;)

**User Story**
**As** a Zally maintainer
**I want** to include OAuth2.0 integration
**In order to:**
- enable OAuth2.0 for others
- simplify build and release process
- enable continuous delivery with CDP (Zalando's continuous delivery platform)
- simplify the project setup

**Acceptance criteria**
- `@zalando/zally-web-ui` can still be published as NPM package
- CDP builds `zally-web-ui-alpha` docker image on every change of `/web-ui`
- OAuth2.0 integration is disabled per default
- docker-compose script doesn't break

**Comment by maxim-tschumak** [comment]
PR is on the way.

WDYT @netme, @ruiaraujo, @tkrop, @rbarilani ?

@roxspring We are aware that you may also have a production instance of Zally (Web UI). These changes should not break anything on your side. But please have a look at the PR once it is there.

**Comment by rbarilani** [comment]
@maxim-tschumak Authentication can be already integrated, see https://github.com/zalando/zally/tree/master/web-ui#add-authentication

**Comment by roxspring** [comment]
Thanks for the heads-up! FWIW we do have the web-ui running internally but actively disable the "production" profile since we don't feel the need to involve authz/n for Zally. I'll keep an eye out for any further pull requests related to this issue just in case.

**Comment by rbarilani** [comment]
@maxim-tschumak As I already said in private: 

> I disagree to "support OAuth2" in a software that is meant to validate swagger specifications

I disagreed when the basic Aauth2 support was introduced in the server code and I still disagree.

In the web-ui I tried to be open also to other auth-mechanism (eg. you can even have an hardcoded list of username and passwords on your nodejs server or basic auth, or whatever your zally server will accept 😄 , take in mind that also the AJAX calls to zally server can be proxied, that's how we do in our zalando instance to add OAuth2 tokens stored in the encrypted session) . It requires a little more work for the user but can be more flexible than TRYING to support every OAuth2 provider out there (in my experience just a few are following "plain" RFC standards, but please correct me if I'm wrong).

As always just my 2 cents.

**Comment by maxim-tschumak** [comment]
@rbarilani Thank you for your input! We will discuss this topic internally since it correlates with internal infrastructure and our continuous delivery platform. There are some trade-offs we have to discuss.

@roxspring and other potential administrators: I'll keep you updated via this issue!

**Comment by maxim-tschumak** [comment]
This issue is opened for a long time and we didn't make any progress - the priorities have shifted.
Closing...
