### ISSUE TITLE
Check if Guidelines Update

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#637]
Please check if the PR https://github.com/zalando/restful-api-guidelines/pull/355 introduces changes which are relevant for the Zally project.

**Comment by maxim-tschumak** [comment]
was created for testing purposes

**Comment by roxspring** [comment]
You creating Zally issues automatically for each Guidelines change? Great!

**Comment by maxim-tschumak** [comment]
@roxspring Yes, would be nice to have things in sync :)
Feedback is very welcome: https://github.com/zalando/restful-api-guidelines/pull/360
