### ISSUE TITLE
Validate results against non-openapi URL responds with misleading schema validation violation [101]

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#640]
Our Zally installation is often used by users submitting urls from GitHub or GitLab, and if you submit the link to the raw view then all works well: 
https://raw.githubusercontent.com/zalando/zally/master/server/src/main/resources/api/zally-api.yaml

However I've seen several users accidentally link to the html rendered view which unhelpfully announces schema violations (because it's trying to validate the html):
https://github.com/zalando/zally/blob/master/server/src/main/resources/api/zally-api.yaml

Additionally, in GitLab at least, some projects may be protected and so the links result in "401 Unauthorized" or "302 Found" (probably should be a 403 Forbidden), either resulting in the html being processed and a schema violation being displayed.

The error is misleading and so I think we ought to do something more informative.

I'm pretty certain that we should be displaying an error for non 200 response codes and not performing the validation. I think we should also be validating the Content-Type of the response, I'd like to think we should white-list the json and yaml mime-types but note that the github example above comes through as text/plain so wonder whether it's better to black-list text/html as the likely problem case. Thoughts welcome.

**Comment by roxspring** [comment]
(Of course one partial answer here might be to provide Zally with an OAuth token it can use against our GitLab installation - I'll explore that separately)

**Comment by tkrop** [comment]
Even authorized users may provide inadequate links. The communication between frontend and backend should provide enough insights to allow a sufficient error message about what is wrong.

**Comment by netme** [comment]
That should be also implemented in #641 . Closing
