### ISSUE TITLE
CLI output JSON formatted

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#648]
For internal CI purposes we're currently running a variation of the CLI tool which outputs in JSON format so that the script running it can do further processing using jq etc. 

Opening this issue to allow a PR to be opened to make the change available upstream.

**Comment by netme** [comment]
Hey @roxspring. I'm really happy that your team is using CLI, however I don't fully agree with this approach. If you are interested in JSON output, why not to trigger API directly and post-process it with jq?

**Comment by netme** [comment]
Maybe you can provide some example and we will see how to make CLI more useful

**Comment by maxim-tschumak** [comment]
I agree with @netme.
@roxspring, please describe your use case

**Comment by roxspring** [comment]
We're using GitLab CI and have a job configured with each API project to check it's swagger.yaml file against Zally. Until recently that would just use the classic cli to fail the build on MUST violations, but consequently SHOULD and lesser violations were going unnoticed. So we decided that the job should be updated so that it additionally uses the GitLab API to add markdown formatted comments to the commit in question. The job consists of a small bash script running within a docker image.

We were already using the freshly built CLI, which itself already knew how to make the requests. I knew that the API required the yaml to be wrapped in an ApiDefinitionRequest and wasn't sure how to easily/reliably do that from a curl command line. So hacking the Zally CLI seemed the simplest way forward.

On reflection, I can understand that it would be ideal for such integrations to use the API directly but I was "put off" by the complexity of forming a suitable request. Perhaps this suggests we should have a 2nd simpler end point that allows direct POSTing of the json/yaml in question to ensure that barrier is kept low.

On the other hand, I'm a little surprised at making the CLI easier to process by a script - automation seems to be the primary use case of such command line tools these days.
We're using GitLab CI and have a job configured with each API project to check it's swagger.yaml file against Zally. Until recently that would just use the classic cli to fail the build on MUST violations, but consequently SHOULD and lesser violations were going unnoticed. So we decided that the job should be updated so that it additionally uses the GitLab API to add markdown formatted comments to the commit in question. The job consists of a small bash script running within a docker image.

We were already using the freshly built CLI, which itself already knew how to make the requests. I knew that the API required the yaml to be wrapped in an ApiDefinitionRequest and wasn't sure how to easily/reliably do that from a curl command line. So hacking the Zally CLI seemed the simplest way forward.

On reflection, I can understand that it would be ideal for such integrations to use the API directly but I was "put off" by the complexity of forming a suitable request. Perhaps this suggests we should have a 2nd simpler end point that allows direct POSTing of the json/yaml in question to ensure that barrier is kept low.

On the other hand, I'm a little surprised at making the CLI easier to process by a script - automation seems to be the primary use case of such command line tools these days.

**Comment by netme** [comment]
@roxspring thanks for clarifications. I see here 2 problems you are trying to solve:

1. Return different status code when `SHOULD` violations are happening
2. Show the comments in GitLab with the violations which have happened

What we can do about it: 

1. Add the extra level parameter which will fail optionally on `SHOULD`, `MAY` violations
2. Add a flag to show less details in the output

Will it be somehow a solution? Ideally for that needs we need a proper GitHub / GitLab integration layer.

**Comment by roxspring** [comment]
For our case we don't necessarily want to change the status code - we only block the build on MUST failures - but we do want to raise the visibility of the violations into GitLab comments rather than just the console logs from various jobs. And actually we're happy with the level of detail from the violations - we just need to transform them into Markdown. Pseudo code for what we're doing goes like this: 

```
processSwaggerWithZally()

if hasAnyViolations() then
  commentOnCommit(violationsRenderedAsMarkdown())
else
  commentOnCommit(thumbsUpEmoji())
end if

if hasMustViolations() then
  stopTheBuildPipeline()
end if
```

A proper Git* integration layer sounds good but I'm not sure how different that would look as GitLab CI seems to have no plugin mechanism beyond running docker based jobs in a pipeline. Ideas welcome though 😃

**Comment by netme** [comment]
@roxspring could you please also provide an example of generated Markdown?

**Comment by roxspring** [comment]
/me suddenly wondering whether a `--markdown` option would have been more popular

Markdown currently looks as follows:
```
* [SHOULD Operation Summary and OperationId Match](http://example.com/#MatchingSummaryAndOperationIdNames)
** OperationId should be the lowerCamelCase version of the summary
** /status GET has operationId 'getStatus' but expected 'getStatusxxx' to match 'Get statusxxx'
```

Actually, looks like there's nothing proprietary in the actual bash script we're using right now so here it is in it's entirety including the jq incantation we're using to generate the markdown:

```bash
#!/usr/bin/env bash

PATH=$1
JSONTOMARKDOWN=".violations[] | \"* **[\(.violation_type) \(.title)](\(.rule_link))**\", \"  * \(.description)\", (.paths[] | \"  * \(.)\")"

echo "Linting $PATH..."
/usr/bin/zally lint --json $PATH > /tmp/zally.json
RESULT=$?

echo "Formatting markdown comment..."
if /usr/bin/jq --exit-status ".violations | length > 0" /tmp/zally.json; then
    /usr/bin/jq \
        --raw-output \
        "$JSONTOMARKDOWN" \
        /tmp/zally.json > /tmp/zally.md
    /bin/sed -e s/^/\ \ /g /tmp/zally.md

    echo "Commenting violations on gitlab commit..."
    /usr/bin/curl \
        --silent \
        --request POST \
        --header "PRIVATE-TOKEN: ${ZALLY_GITLAB_TOKEN}" \
        --form "note=</tmp/zally.md" \
        --form "path=$PATH" \
        --form "line=1" \
        --form "line_type=new" \
        ${CI_PROJECT_URL}/../../api/v4/projects/${CI_PROJECT_ID}/repository/commits/${CI_BUILD_REF}/comments
    
else
    echo "Commenting success on gitlab commit..."
    /usr/bin/curl \
        --silent \
        --request POST \
        --header "PRIVATE-TOKEN: ${ZALLY_GITLAB_TOKEN}" \
        --data "note=%F0%9F%91%8D" \
        --data "path=$PATH" \
        --data "line=1" \
        --data "line_type=new" \
        ${CI_PROJECT_URL}/../../api/v4/projects/${CI_PROJECT_ID}/repository/commits/${CI_BUILD_REF}/comments
fi

exit $RESULT
```

**Comment by netme** [comment]
Yeah, that's why I was asking :-)  

We can think about keeping `--format=markdown` option, that can be a deal breaker, because we will be able to generate e.g. HTML reports. 

What we still need is to:
- agree how the format should look exactly
- maybe think about short / long versions of the format
- sync `text` and `markdown` formats, so they provide consistent output

@maxim-tschumak @roxspring any ideas on that? 💡 

Don't get me wrong, I wanted to avoid showing raw output from API, because in the end API can serve it perfectly .

**Comment by roxspring** [comment]
Sounds good to me. The only thing I'd add:
- agree a positive (non-blank) output when no violations are found

Do you have ideas / improvements on the Markdown formatting to suggest?

**Comment by netme** [comment]
Created a ticket #652 for `--format` option

**Comment by netme** [comment]
And another optional ticket #653
