### ISSUE TITLE
Zally reports violation of rule #110 for endpoints returning binary data

### ISSUE THREAD

**Issue by mkulak** [zalando/zally#650]
I have endpoint which returns file content as binary
```yaml
  "/reports/{report-id}":
    get:
      produces:
        - application/pdf
      responses:
        '200':
          description: Return report as a PDF file
          schema:
            type: file
```
Zally reports violation: 
```
MUST – Response As JSON Object
Always Return JSON Objects As Top-Level Data Structures To Support Extensibility
Rule: https://zalando.github.io/restful-api-guidelines/#110
```

But in fact this is totally valid according to [rule 168](https://zalando.github.io/restful-api-guidelines/#168)

**Comment by netme** [comment]
@maxim-tschumak your input will be needed :-) 

For which `produces` section values we should trigger that rule? I'l vote for `application/json` and `application/problem+json`

**Comment by netme** [comment]
And should we also make a `HINT` violation for the formats other than JSON?

**Comment by maxim-tschumak** [comment]
As @roxspring pointed out, the rule [110](https://zalando.github.io/restful-api-guidelines/#110) isn't about JSON as a used format. It's about the top-level data structure (object `{items: [article1, article2]}` instead of an array `[article1, article2]`).

> For which produces section values we should trigger that rule? I'l vote for application/json and application/problem+json

Let's restrict the `produces` formats to `application/.*json.*` (or even `.*json.*`)

> And should we also make a HINT violation for the formats other than JSON?

I wouldn't add a new HINT violation to avoid voice (since in the most cases it will be a false-positive).

**Comment by tkrop** [comment]
A media type is defined to have the following form:

```
top-level type name / subtype name [ ; parameters ]
top-level type name / [ tree. ] subtype name [ +suffix ] [ ; parameters ]
```
As a consequence the actual regex must look like:
```
^[^/]*/(json|[^+;]+\+json)(;.*)?$
```

**Comment by mkulak** [comment]
I propose to reverse this logic.
Since we assume that JSON is default data type I think it makes sense to check for it by default. And skip this check only for those endpoints that both have content type specified and value of this content type doesn't contain substring "json".
What do you think? @netme @tkrop  @maxim-tschumak

**Comment by netme** [comment]
@mkulak I like your idea. Ideally we should have a rule which checks that the content-type of endpoints is specified. @maxim-tschumak any plans to introduce such rule?

**Comment by maxim-tschumak** [comment]
It's not really related to design of an API. But we were thinking about best-practices section for OpenAPI specifications - this would be a good candidate!
