### ISSUE TITLE
Add --format flag to Zally CLI

### ISSUE THREAD

**Issue by netme** [zalando/zally#652]
In order to make Zally Command Line Utility (CLI) usable in different Continuous Integration platforms, we want to add more formatting options. Therefore, we need to implement an extra `--format` flag. 

## Acceptance Criteria
```
As a Zally CLI user
I want to provide the --format flag when running CLI
So that Zally will format its output in plain text or markdown
```

## Example
```
./zally --format=markdown
```

## Expected text output:

```
MUST Use Problem JSON
  Operations Should Return Problem JSON When Any Problem Occurs During Processing Whether Caused by Client Or Server
  https://zalando.github.io/restful-api-guidelines/#176
    /products GET 429
    /products/{product_id} GET 418
    /products/{product_id} GET 429
    /products/{product_id} PATCH 400
    /products/{product_id} PATCH 429
```

## Expected markdown output

```markdown
### `MUST` [Use Problem JSON](https://zalando.github.io/restful-api-guidelines/#176)

> Operations Should Return Problem JSON When Any Problem Occurs During Processing Whether Caused by Client Or Server
        
- /products GET 429
- /products/{product_id} GET 418
- /products/{product_id} GET 429
- /products/{product_id} PATCH 400
- /products/{product_id} PATCH 429
```

## Expected output when no violations happened:

```
Congratulations! No violations found.
```

**Comment by netme** [comment]
### Questions / TODO:
- [ ] Should we also distinguish between text output with colors and without colors? 
- [ ] Provide text example
- [ ] Provide markdown example
- [ ] Provide example for no violations output
- [ ] Should "no violation" differ in markdown / text outputs?

**Comment by netme** [comment]
@roxspring , @maxim-tschumak could you please check the examples?

**Comment by maxim-tschumak** [comment]
Looks good!

> Should we also distinguish between text output with colors and without colors?

Let's keep it simple :)

> Should "no violation" differ in markdown / text outputs?

IMHO, it can be the same

> How about Short / Long / Custom formats for every single violation (example: git log --pretty)

Great idea!

**Comment by roxspring** [comment]
Looks good to me too!

> Should we also distinguish between text output with colors and without colors?

How about we reserve a name now for a text-only format, but don't rush to implement it. I only mention this because if we call the current format "text" then that doesn't leave us much room to add an uncolored version without the options being confusing. I'd suggest:
- plain (not implemented initially)
- pretty (default ansi colored text as seen currently)
- markdown

> Should "no violation" differ in markdown / text outputs?

Perhaps might make more sense if we add html/other formats later but for now it doesn't seem necessary.

> How about Short / Long / Custom formats for every single violation (example: git log --pretty)

Would be cool but I'd also be happy with it moving into the "Ideas for the future" section too.

**Comment by netme** [comment]
Thanks @maxim-tschumak and @roxspring for the valuable input. Let me proceed with the implementation then

**Comment by netme** [comment]
Created few follow-up stories:
- #694 
- #695 
- #696
