### ISSUE TITLE
Secure With OAuth2 Rule issues

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#656]
SecureWithOAuth2Rule (104) is broken into 3 checks, arguably verifying 5 different things:
1. checkSecurityDefinitions (MUST)
  a. Ensure "oauth2" security definition exists
  b. Ensure schemes does not contain "HTTP"
2. checkPasswordFlow (SHOULD)
  a. Ensure that only application flow is used
3. checkUsedScopes (MUST)
  a. Ensure that all scoped operations refer to a defined scope
  b. Ensure that all operations are scoped.

(Aside: 3 above seems to leave an obvious gaping hole which may be worth checking: Ensure that all defined scopes are used by some operation)

Initially we disabled the rule for our installation since all of our services are defined as "schemes: [http, https]" and therefore everything was failing. We've recently hit situations where 3a would have avoided mistakes and so would like to enable the rule. Fixing our usage of schemes and therefore complying with 1b seems very reasonable BUT we disagree with 3b because we have some operations which need to be accessed by authenticated users but not with any particular scope. This leaves us with a puzzle because we'd like to enable part, but not all of the rule.

I can see a number of options available to resolve this and so wanted to consult the team:

1. Just add some "authenticated" scope to our infrastructure and run the original Zally rule untouched (Actively costing this option up in case it's viable)
2. Refactor 3 into two separate rules so that 3a can be used while 3b is ignored.
3. Split 3 into two separate checks and add support for ignoring specific checks.
4. Implement #495 or #446 so that rule 104 can be ignored for specific paths/operations where anonymous usage is needed (Pretty sure it would be welcome but not sure of the easiest route there!)

Particularly interested to hear what @maxim-tschumak and @netme would recommend, and whether the changes would be welcome upstream.

**Comment by roxspring** [comment]
Chatting with a colleague I'm reminded that actually 3b above is implementing rule "Define and Assign Access Rights (Scopes) [105]" and isn't at all necessary to implement "Secure Endpoints with OAuth 2.0 [104]". Based on that I'm very tempted to split 3b out into a new rule implementation for 105 which we can ignore internally while having 104 enabled.

Thoughts?

**Comment by maxim-tschumak** [comment]
> Based on that I'm very tempted to split 3b out into a new rule implementation for 105 which we can ignore internally while having 104 enabled.

I agree and support the proposed change.

PS. @roxspring to your original question: I would favor solution **3** (and eventually 4) to make Zally usage more convenient for your and any potential installations.
