### ISSUE TITLE
Update Spring.Boot to 2.0.0

### ISSUE THREAD

**Issue by netme** [zalando/zally#659]
Spring.Boot 2.0.0 is out 🎉 

### Steps:
1. Upgrade to Spring.Boot 2.0.0
2. Bump dependencies
3. Make it working

**Comment by netme** [comment]
Found out that `zmon-actuator` is not compatible with the latest Spring.Boot. 

@maxim-tschumak do we really need it? Can we export metrics using standard `spring-boot-actuator`?

**Comment by maxim-tschumak** [comment]
@netme I believe we can remove `zmon-actuator`.
We monitor technical metrics via K8S and product metrics via the `/statistics` endpoint. The only additional endpoint is the health check endpoint `/health` which is used as a readiness probe in K8S.
