### ISSUE TITLE
Refactor Context Pointer: String -> JsonPointer

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#715]
In order to introduce the support of the OpenAPI3 earlier, we had to introduce some technical dept. As pointed out by @roxspring, the Pointer type (currently `String`) in the Context is suboptimal.

**As** developer and maintainer of Zally
**I want** to change the type of the pointer to `com.fasterxml.jackson.core.JsonPointer`
**So that** the implementation becomes less error-prone

**Comment by roxspring** [comment]
@maxim-tschumak think we can close this now.

**Comment by netme** [comment]
Closing
