### ISSUE TITLE
cli refusing to run

### ISSUE THREAD

**Issue by upasanachatterjee** [zalando/zally#720]
The server and UI work perfectly. When trying to set up the cli, i build the binary but the cli doesn't run. 

i can run `./zally --help` and pull up the help message. But cannot get anything else work. Not a problem with Go, as I can get other CLIs to work.

Attaching terminal output.
[Terminal Saved Output.txt](https://github.com/zalando/zally/files/2040789/Terminal.Saved.Output.txt)

**Comment by roxspring** [comment]
Not certain what's going wrong for you but I'd recommend using a browser or curl to confirm that the server is serving where you expect - if http://localhost:8080 is the right url then browse to http://localhost:8080/supported-rules and you should get a JSON response showing the rules.

**Comment by maxim-tschumak** [comment]
Agree with @roxspring. Looks like you have something else running on `localhost:8080` - Zally server would not return any HTML in case of 404.

**Comment by maxim-tschumak** [comment]
@upasanachatterjee I could not reproduce the error. Have you tried the [precompiled version of the CLI](https://github.com/zalando/zally/releases/tag/1.1.0)?

**Comment by upasanachatterjee** [comment]
I tried that as well. Still not working.

**Comment by upasanachatterjee** [comment]
I can manage to get the CLI to work now, but only when the UI is not running. If the UI runs, then the CLI just stops working. Was this the way Zally was set up?

**Comment by maxim-tschumak** [comment]
@upasanachatterjee How do you start the UI? Do you use the docker-compose script?

Zally UI and CLI are completely independent, but they do both need the Zally Server to do the actual work.

**Comment by upasanachatterjee** [comment]
@maxim-tschumak If I run the docker compose script `./build-and-run.sh` I get both the server and the UI up and running. If I then cd to my go folder where the code for the CLI is located and try to run that, I get the errors that I mentioned in my very first post. 

But for some reason, when I just build and run the server using `./gradlew clean build` and `./gradlew bootRun`, and then cd to where the CLI is located, CLI works fine.

**Comment by maxim-tschumak** [comment]
> But for some reason, when I just build and run the server using ./gradlew clean build and ./gradlew bootRun, and then cd to where the CLI is located, CLI works fine.

This is good :)

> If I run the docker compose script ./build-and-run.sh I get both the server and the UI up and running. If I then cd to my go folder where the code for the CLI is located and try to run that, I get the errors that I mentioned in my very first post.

In this case (docker-compose), Zally Server runs on port `8000` (`--linter-service "http://localhost:8000/"`).

**Comment by upasanachatterjee** [comment]
ah that works perfectly thank you so much! I could swear I tried running the CLI on `localhost:8000` but that must have been what I missed
