### ISSUE TITLE
AST bugs

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#734]
Have run into some weird bugs in the AST related code, particularly given this additional test in `ContextTest.kt`:

```kotlin
    @Test
    fun test2() {
        val content = """
            openapi: '3.0.0'
            info:
              title: Things API
              version: 1.0.0
            paths:
              /things:
                post:
                  description: Description of /things
                  parameters:
                    - "${'$'}ref": "#/components/parameters/P"
                  responses:
                    200:
                      description: Description of 200 response
            components:
              parameters:
                P:
                  name: p
                  in: query
                  description: Parameter p
                  required: true
                  schema:
                    type: string
                    format: uuid
                    default: "SchemaDefault!!"
                    example: "SchemaExample!!"
                  example: "ParameterExample!!"
            """.trimIndent()

        val firstContext = Context.createOpenApiContext(content)!!
        val firstValueA = firstContext.api.components.parameters["P"]!!.example
        val firstValueB = firstContext.api.paths["/things"]!!.post.parameters[0].example
        val firstPointerA = firstContext.violation("", firstValueA).pointer
        val firstPointerB = firstContext.violation("", firstValueB).pointer

        assertThat(firstPointerA)
                .isSameAs(firstPointerB)
                .hasToString("/components/parameters/p/example")

        // fresh context + same lookups but reverse order
        val secondContext = Context.createOpenApiContext(content)!!
        val secondValueB = secondContext.api.paths["/things"]!!.post.parameters[0].example
        val secondValueA = secondContext.api.components.parameters["P"]!!.example
        val secondPointerB = secondContext.violation("", secondValueB).pointer
        val secondPointerA = secondContext.violation("", secondValueA).pointer

        assertThat(secondPointerB)
                .isSameAs(secondPointerA)
                .hasToString("/paths/~1things/post/parameters/0/example")
    }
```

The main problem this highlights is that although two paths to the same resolved object get the same JsonPointer, which pointer you get depends on the order of looking them up. On the face of it, this may seem reasonable but I've found it leading to inconsistent behaviour in tests where I regularly have to switch the expectation. You'd think that the example instances would have been picked up by the `ReverseAstBuilder` in a consistent order and therefore resolve them during context creation, but it turns out that the initial traversal doesn't consider inherited get* methods and so doesn't spot shared get such as `getExample()`. Will modify the initial traversal to use `.getMethods()` rather than `.getDeclaredMethods()` and add some unit tests for which methods get traversed.

A second oddity is that the `firstPointerA` has lower-cased the `P` such that the pointer doesn't correctly reference the right location. `JsonPointers.escape(Method,Object[])` is doing the wrong thing here so will add a fix and unit test.

Thirdly when debugging the above in Idea the pointers were coming out completely differently as `/toString/entrySet/example`:
![image](https://user-images.githubusercontent.com/783694/41726548-4fe224a8-756a-11e8-8f44-a54d24244c9e.png)
This appears to be because the pointers were being built by MethodCallRecorder rather than successfully looked up from the ReverseAST, AND the debugger was calling `toString()` on the relevant objects while I was stepping through. Fixing the intial traversal hides the problem but only updating the pointer if traversing the method seems a healthy step forward too. Will add a unit test if I can think of one.

PR coming soon.

**Comment by maxim-tschumak** [comment]
Regarding the first issue: the context object is **not** stateless - this is the biggest downside of this design.

**Comment by roxspring** [comment]
Sure it's not stateless, but the design does involve priming the `ReverseAST` such that many of the pointers are already known before the object model is interrogated. The problem is that the priming skips chunks of the model, leaving those to be identified and named by the ad-hoc `MethodCallRecorder`, when they could be easily and correctly primed. Additionally the priming logic (accidentally) prefers to name the pointers after their appearance in the `/paths` structure over the shared locations in `/components` or `/definitions` etc, which I find to be unfortunate.
