### ISSUE TITLE
Wrong documentation property name "ignoreRules"

### ISSUE THREAD

**Issue by tk** [zalando/zally#759]
The ignore rules properties in the API definition is named "ignoreRules" instead of the working property name "ignore_rules".

https://github.com/zalando/zally/blob/b4877cbd05608ff7cb638ffd2dbab3162a3ec942/server/src/main/resources/api/zally-api.yaml#L205

**Comment by maxim-tschumak** [comment]
Good catch, thanks!

**Comment by vadeg** [comment]
This was fixed in #852
