### ISSUE TITLE
Parse and Conversion Problems cause 500

### ISSUE THREAD

**Issue by ddufourboivin-zalando** [zalando/zally#773]
# How to reproduce?

Access [Zally web UI](https://zally.zalando.net/).

Lint this:
```yaml
swagger: "2.0"
```

Result:
> ERROR
> Ooops something went wrong!

# Expected Result

We should get a violation of [rule 101](https://opensource.zalando.com/restful-api-guidelines/#101) _Must: Provide API Specification using OpenAPI_, since the specification is not valid _Open API_.

# Root Cause

This specification makes the converter (from Swagger 2 to OpenAPI 3) throw an exception. Instead of crashing, _Zally_ should detect that an form a proper violation instead of crashing with a 500.

**Comment by ddufourboivin-zalando** [comment]
# PR
https://github.com/zalando/zally/pull/794

**Comment by roxspring** [comment]
This looks fixed to me.

**Comment by tkrop** [comment]
Agreed.
