### ISSUE TITLE
Upgrade to swagger-parser 2.0.2 or newer

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#784]
Looked at patching https://github.com/zalando/zally/issues/765 upstream and discovered it was [already fixed](https://github.com/swagger-api/swagger-parser/commit/fc28f24204531fa13a7e69e8b8c576a0decd5bbe) a month ago but not yet released.

Once the fix is released we should upgrade to the fixed version (presumed to be swagger-parser 2.0.2) and remove the hack added in https://github.com/zalando/zally/pull/781. 

Note that 2.0.1 is also available and might be worth upgrading to, but doesn't address this particular issue. A 2.0.2 release appears to be imminent and is planned in https://github.com/swagger-api/swagger-parser/issues/780

**Comment by tkrop** [comment]
:+1: Wow, I feel so stupid. Why haven't I sought about looking for updates first :)

**Comment by ddufourboivin-zalando** [comment]
I know that feeling, @tkrop ...

**Comment by roxspring** [comment]
Trust me - I feel the same!

It does make me wonder whether we should take advantage of Gradle's dependency version ranges to keep in lockstep with swagger parser patch versions e.g. `io.swagger.parser.v3:swagger-parser:2.0.+`, or maybe minor/major versions too.  I'm aware this potentially leads to a philosophical debate on build determinism vs developer laziness, but there's at least `com.fasterxml.jackson.module:jackson-module-kotlin:2.9+` already in use so it seemed worth questioning.

**Comment by jmini** [comment]
Swagger-Parser `2.0.2` was released: https://github.com/swagger-api/swagger-parser/releases/tag/v2.0.2
