### ISSUE TITLE
next release version cut?

### ISSUE THREAD

**Issue by JonKohler** [zalando/zally#792]
Hey all - silly question maybe, but I didn't see a clear milestone/tracker for when the next release is going to be cut from master?

1.1 is getting a bit long in the tooth, and I wanted to check this out for a use case that we have, just wanted to make sure I was using the right stuff.

**Comment by maxim-tschumak** [comment]
I'm hoping to release a new version after the [Rule Sets](https://github.com/zalando/zally/issues/551) and full [support for OpenAPI3](https://github.com/zalando/zally/issues/714) are implemented.

You can always build the current version from the master branch. The master branch is stable and can be used as a rolling release.

Feel free to ask for support - we are happy to help :)

**Comment by JonKohler** [comment]
Great! a bit of context, I'm working on building a "validation pipeline" for our various APIs within our platform.

General idea is it goes from the basics of "document cleaniness" (is this an ugly YAML?) through OAI spec validation (lots of tools), style validation (zally), to Internal and External developer experience (server side generation, client side generation, using various tools), unit testing with mocking, functional testing against real APIs, all the way through publishing it to our developer portal.

That way, we can tell, with pin point certainty, that not only is the spec "right", but it works in every sense of the word, so developers can just "run" without question.

Zally is a bit corner stone to that, IMHO, as having all of the various platform APIs subscribe to the same styling and rulesets will make our platform feel like it was authored by one team, but give us the speed of micro-teams.

**Comment by maxim-tschumak** [comment]
> [..] having all of the various platform APIs subscribe to the same styling and rulesets will make our platform feel like it was authored by one team, but give us the speed of micro-teams.

This was exactly the intention behind our [Guidelines](https://opensource.zalando.com/restful-api-guidelines/) and Zally project. 

Sounds like a great use-case for Zally!

**Comment by maxim-tschumak** [comment]
@JonKohler Can I close the issue or do you have any further questions?

**Comment by JonKohler** [comment]
yes, we can close this. Thanks!
