### ISSUE TITLE
Flexible Case Checking Rules

### ISSUE THREAD

**Issue by roxspring** [zalando/zally#813]
There are a number of rules which check the case of various strings:

- `SnakeCaseInPropNameRule`
- `SnakeCaseForQueryParamsRule`
- `PascalCaseHttpHeadersRule`
- `KebabCaseInPathSegmentsRule`

For our installation, we prefer camelCase for properties and query parameters, and I'm tempted to create some additional rules to check the case of path (and form, body, cookie?) parameters and shared definitions. Rather than maintain separate in-house rules I propose that I/we:

- Rename the rules into a consistent `CheckCaseOf*Rule` pattern
- Generalize the above rules such that the required case is parameterized
  - Implies that rule titles might become less specific "Use snake_case (never camelCase) for Query Parameters" would need to become "Query Parameters Use Correct Case"
- Also generalise the shared list of cases & regexes so that adding new ones becomes a non-code change

Relevant configuration would become something like:

```
Cases {
  camelCase: ^[a-z]+(?:[A-Z][a-z]+)*$
  snake_case: ^[a-z0-9]+(?:_[a-z0-9]+)*$
  kebab-case: ^[a-z]+(?:-[a-z]+)*$
}

CheckCaseOfPropertyNamesRule {
  case: snake_case
}

CheckCaseOfQueryParametersRule {
  case: kebab-case
}

CheckCaseOfHeaderParametersRule {
  case: SCREAMING_SNAKE_CASE    <- config time error!!
}
```

The case checking and error message generation should be done in a shared utility class so that we produce helpful error messages along the lines of "Query Parameters should be kebab-case but 'nameOfThing' appears to be camelCase".

It's tempting to suggest that we implement each of these as separate checks within a single rule but the existing ones are each tied to different guidelines so that would require us to rewrite those guidelines into one or revise our rule vs check model.

Objections?

**Comment by maxim-tschumak** [comment]
I understand your use-case, let's try to find a solution which fits us all.

> Generalize the above rules such that the required case is parameterized
Implies that rule titles might become less specific "Use snake_case (never camelCase) for Query Parameters" would need to become "Query Parameters Use Correct Case"

It doesn't work in our current design - this will break the integrity between Zally `Rule` implementation and the actual rule in the guidelines (e.g. title cannot be the same anymore).

What do you think about:
1. Shared pattern matching utility class for fields and properties
2. A new configurable rule in the Zally package which you can activate for your installation
3. Rules in Zalando package and the new generic Zally rule use the same utility class/function

PS. I'll be offline for the next 1,5 weeks. @tkrop @ddufourboivin-zalando please take over and support @roxspring

**Comment by roxspring** [comment]
Interesting idea. Existing Zalando rules stay unconfigurable and specific, Zally gains a new rule capable of checking the case of various things, they both use the same underlying logic to implement the check. Everybody is happy.

PS. I'll be out for the next week too so you'll likely be back by the time I have anything ready, and in the meantime everybody can have some peace! Enjoy your break!
