### ISSUE TITLE
Migrate checks to operate on the context object to support OpenAPI 3 (follow-up)

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#834]
Follow-up issue for #714.

After implementing the initial support for OpenAPI3 we have to adjust the check implementations. Instead of operating on the Swagger object, the checks have to use the `Context` object. Doing this, the checks become universal - applicable against Swagger2 and OpenAPI3 specifications.

Most important rules have already been refactored in #714.

**Acceptance Criteria:**
1. The following checks are refactored to use the `Context` object
2. Minimal specifications are used in the tests

## List of `Rules` to be refactored
- [x] SecureAllEndpointsWithScopesRule (currently not used in production) ([PR](#825))
- [x] ExtractBasePathRule ([PR](#861))
- [x] HyphenateHttpHeadersRule (Removed, see [discussion] (https://github.com/zalando/zally/issues/834#issuecomment-422937952)) ([PR](#607))
- [x] NoProtocolInHostRule ([PR](#856))
- [x] NoUnusedDefinitionsRule ([PR](#872))

**Comment by vadeg** [comment]
Rule {{HyphenateHttpHeadersRule}} linked to rule 131 in API Guidelines but there is no such rule. Should we remove this rule?

**Comment by maxim-tschumak** [comment]
@vadeg You are right, we should remove the check. Would you take over or should I do this?

**Comment by vadeg** [comment]
@maxim-tschumak I will take over in scope of PR for this ticket.

**Comment by maxim-tschumak** [comment]
@vadeg great, thanks!

**Comment by roxspring** [comment]
`AvoidXZallyIgnoreRule` operates on `JsonNode` not `Swagger` so I think can be considered done.

**Comment by roxspring** [comment]
Thanks for all the reviews and merges everyone!

They should mean that we can tick these off now:
- `ExtractBasePathRule`
- `HyphenateHttpHeadersRule`
- `NoProtocolInHostRule`

And hopefully #872 will tick `NoUnusedDefinitionsRule` and allow us to close the issue.

**Comment by maxim-tschumak** [comment]
Thanks for your contributions! And sorry that we cannot always respond in one-two days.
Maybe we should set up another communication channel. Something like Slack.

What do you think? @roxspring @tkrop @ddufourboivin-zalando

**Comment by roxspring** [comment]
You're welcome! Instant responses are not necessary, I'm comfortable with the usual response time of a few working days.

Slack or similar would be helpful for occasionally requesting attention on a PR, or for discussing thoughts before they're ready to be tracked as issues and pull requests.

**Comment by maxim-tschumak** [comment]
@roxspring @tkrop @ddufourboivin-zalando please join zally [maintainers Slack chat](https://join.slack.com/t/zally/shared_invite/enQtNDU5OTEwMjQ2NTMxLTJmYTNlZjY3ZTUyMmRkMjJjZWEwYjM3ZDlmMzY1ZDY3ZWQ4OTAxZGVjN2QzMGM4OTQ1YWEyOWQyMDMyZWFiMTk).

**Comment by roxspring** [comment]
Think this is done now :)

**Comment by ddufourboivin-zalando** [comment]
@maxim-tschumak : Just updated the _List of Rules to be refactored_ section in the description of this issue with the latest status of all of them.
