### ISSUE TITLE
Optimize review-statistics calculations

### ISSUE THREAD

**Issue by maxim-tschumak** [zalando/zally#873]
We have pretty much linting requests these days. This is great :), but the `/review-statistics` endpoint does not cope with the load. Querying last week statistics can take up to one minute. The main reason is the **size** of the review statistics which are being transmitted from database to server and then back to the client.

I propose to exclude `review` and `violations` from the [`review-statistics`](https://github.com/zalando/zally/blob/master/server/src/main/resources/api/zally-api.yaml#L253) API resource and only send aggregated numbers - the actual statistics.

**CAUTION:** This is a breaking change of Zally API.

@roxspring Do you use the `/review-statistics` endpoint?

**Comment by roxspring** [comment]
I have a long-standing TODO item to start looking at the review-statistics and see what I can learn from them... but no I'm not using the endpoint yet and so won't notice any API breakage.

**Comment by maxim-tschumak** [comment]
Great! I will prepare a PR.
