### ISSUE TITLE
Replace `recursiveness` by `recursion`

### ISSUE THREAD

**Issue by ddufourboivin-zalando** [zalando/zally#883]
```java
    /**
     * This test runs all rules against an API specification with recursive references. It prevents check developers
     * from StackOverflow exceptions during the check execution.
     *
     * General advice: Don't use `hashCode` or `toString` methods on the OpenAPI elements since they don't support
     * recursiveness. Keep in mind that these methods can be called implicitly (e.g. when putting objects in a Set).
     */
    @Test
    fun `all rules must be able to cope with recursive api specifications`() {
```

`recursiveness` is not a word.
The word you are looking for it ~~`recursivity`~~ `recursion`.

Perform a project wide search to make sure that mistake is not anywhere else.

**Comment by maxim-tschumak** [comment]
https://en.oxforddictionaries.com/definition/recursiveness ;)

**Comment by ddufourboivin-zalando** [comment]
That being said, the term used in the computer world is normally _recursivity_, so I would still propose that change.

**Comment by maxim-tschumak** [comment]
Yes, let's change it to _recursivity_.

**Comment by roxspring** [comment]
Don’t think I’d come across “recursivity” before this issue but “recursiveness” isn’t especially common either. In conversations I’ve had “recursive” is typically a Boolean attribute, not a continuous variable with multiple degrees. 

How about finding a way to simplify the language, rephrasing to use “recursive” and some additional words? (Haven’t looked up the context where we use it and so don’t have a concrete suggestion right now)

Thanks,

Rob

**Comment by roxspring** [comment]
Out of curiosity I just looked up the 3 words on google trends and was a little surprised to see that _recursivity_ is slightly more common than _recursiveness_. However, both disappear in the bottom of the chart when [compared to _recursion_](https://trends.google.com/trends/explore?q=recursiveness,recursivity,recursion).

**Comment by maxim-tschumak** [comment]
This is what I call **research**!

**Comment by ddufourboivin-zalando** [comment]
Also, the _Kotlin_ term for it is _Recursion_. It should definitely be it. Changing this issue.

**Comment by roxspring** [comment]
Can be closed now.
