### ISSUE TITLE
Editor diplays only four lines on Firefox

### ISSUE THREAD

**Issue by ISO50** [zalando/zally#889]
![zally](https://user-images.githubusercontent.com/6464494/48122109-f8069780-e276-11e8-9ab7-9111fa938f97.png)

**Comment by maxim-tschumak** [comment]
I can also reproduce the described behavior - we have to fix it.

**Comment by roxspring** [comment]
Reproduces on Windows too. Also the layout behaviour only gets more broken after hitting Validate:
- Editor scroll area expands to expected height, but only a handful of lines of content at the top
- Violations area is not separately scrollable
- Entire window ends up scrollable

**Comment by tkrop** [comment]
Interestingly, the behavior even changes, when you use `ctrl-+/-` to change the browser zoom.

**Comment by tkrop** [comment]
Lets try to update the libraries.

**Comment by tkrop** [comment]
This seems to be outdated. At least I cannot confirm this bug any longer.
