### ISSUE TITLE
Incorrect Severity of Rule [151] (MUST Specify Success and Error Responses)

### ISSUE THREAD

**Issue by tkrop** [zalando/zally#891]
Currently MAY instead of MUST.

**Comment by tkrop** [comment]
Oh, I forgot, that we have a different perspective on Check level. Anyhow, wording and severity do not fit together. The rule says MUST, the check says MAY, the text says HAS TO:

```
MAY – Specify Success and Error Responses
operation has to contain the default response
Rule: https://zalando.github.io/restful-api-guidelines/#151
```

So I would suggest to use at least SHOULD for `checkContainsDefaultResponse`.

**Comment by natami** [comment]
Any news on this bug?

**Comment by roxspring** [comment]
No news as such but pull requests are always welcome.

Firstly would need to change the method annotations in https://github.com/zalando/zally/blob/master/server/src/main/java/de/zalando/zally/rule/zalando/JsonProblemAsDefaultResponseRule.kt

Secondly, I would fully expect this change to affect the cli integration tests - so expectations will likely need updating there too.

For bonus marks we ought to consider a test over all the rules asserting that all checks <= rule level and at least one check == rule level.
