### ISSUE TITLE
enum value convention

### ISSUE THREAD

**Issue by msoub** [zalando/zally#907]
Hello,

First of all, thank you for this tool!

I didn't see any guidelines regarding the naming of enum values and from the different examples, it seems that there is none. Wouldn't that be interesting to have one clear convention?

**Comment by roxspring** [comment]
[CaseCheckerRule](https://github.com/zalando/zally/blob/master/server/src/main/java/de/zalando/zally/rule/zally/CaseCheckerRule.kt) will validate enum properties as any other property, which probably is the right thing to do when truely thinking API-first.

However, in-house we generate Java code from the API specs and so tend to use `camelCase` property names generally, but `SCREAMING_SNAKE_CASE` for enums, except where it's a descriminator referencing a type using `PascalCase`. Admittedly we could configure `checkPropertyNames()` against any of the patterns above but that becomes a fairly lax check. The alternative seems to be to add `checkEnumPropertyNames()`, `checkDiscriminatorEnumPropertyNames()` checks and restrict `checkPropertyNames()` to the other cases which all feels a little verbose... but maybe viable.

What conventions are you thinking of @msoub?

**Comment by msoub** [comment]
I think the `SCREAMING_SNAKE_CASE` is arguable in the sense that I'm not sure there is a need to _emphasize_ enum values compared to other values.
People from [Stripe](https://stripe.com/docs/api/checkout_sessions) — who have a rather good API — tend to use regular `snake_case` which looks pretty much fine to me.

Regarding the discriminator case — I hope you enjoyed the pun :) — I don't really have an opinion, however I'm not sure to see the need to differentiate it.
