### ISSUE TITLE
Use multistage docker builds for better easy of use

### ISSUE THREAD

**Issue by 7DataBits** [zalando/zally#913]
Creating multistage dockerfiles would improve ease of use for first time users who just want to get a local version up and running. Since there are no official readily built images available users have to setup up a minimal build environment to use the software. (also see #761 )
docker-compose.yaml is already available but only works if the project has already been built locally which requires stuff like yarn, python etc. to be installed on the host machine.

Multistage Docker Builds: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by roxspring** [comment]
Have wondered about this myself in the past - would be especially useful for getting web-ui building under Windows (without using WSL)!

Any objections from the core Zalando team?

**Comment by maxim-tschumak** [comment]
I like this approach

**Comment by vadeg** [comment]
Fixed.
