### ISSUE TITLE
Add yarn and python2 (and 3?) as a technical dependency in operation documentation

### ISSUE THREAD

**Issue by 7DataBits** [zalando/zally#915]
Tried to build the checked out repository today and ran into 2 issues with uninstalled packages on my host machine.
* Yarn was not installed (relatively easy fix through installing yarn)
* Had no python2 (only python in version 3) installed

So at least adding these mandatory dependencies to the list would be nice. (No idea about the exact needed minium versions though)
Also see #913 for solving this issue on another level

**Comment by vadeg** [comment]
@7DataBits I have not found any dependency on Python. Where did you get this?

**Comment by vadeg** [comment]
I am closing it. Feel free to re-open the issue if needed.
