### ISSUE TITLE
Local zally Windows installation doesn't work 

### ISSUE THREAD

**Issue by vivanov19** [zalando/zally#919]
Hello, 

I followed the README documents and related issues and almost installed zally locally on the Windows 10 machine. I am able to execute all gradlew tasks, but when I am executing the bootRun it stops after initiating the back-end server 0% as script indicated). Back-end (localhost:8000) for sure works since the command `zally --linter-service "http://localhost:8000" --format pretty lint no_must_violations.yaml` brings the meaningful results. I can also get the list of the rules from the browser executing http://localhost:8000/supported-rules as well as all 200+ tests executed successfully.  Attached is the complete output from my DOS shell. 

On the other hand, it never brings front-end running on 8080 port. I am guessing it might be some proxy setting between zally back-end and front-end need to be done, but not sure.

I also successfully mounted / build the web-ui component separately with zally server running in its current state. Again all build tasks are complete successfully with npm and / or yarn, but I can run neither dev nor production builds. Both brings similar exceptions ''NODE_ENV' is not recognized as an internal or external command,'.  DEV mode also brings some JS exception. Again, the whole output from another DOS shell is attached.

Please let me know if any other information needed.

[FullZallyDOSShellOutput.txt](https://github.com/zalando/zally/files/2773991/FullZallyDOSShellOutput.txt)

[WebUIZallyDOSShellOutput.txt](https://github.com/zalando/zally/files/2774017/WebUIZallyDOSShellOutput.txt)

**Comment by roxspring** [comment]
From your first paragraph it's pretty clear that you have the server running successfully on port 8000, and the command line working too. The front-end on port 8080 come from the web-ui which you're having trouble with.

The command `NODE_ENV=development nodemon server.js` being run isn't going to work directly under Windows as 1) it's attempting to set an environment variable in the command line and 2) nodemon is unlikely to be on the path. You should be able to do the equivalent by running `set NODE_ENV=development` and then `node_modules\.bin\nodemon.cmd server.js`. That alone isn't enough to get the web-ui running for me, so I suspect more changes are needed to get up and running directly under Windows.

For what it's worth, I routinely build and run Zally under Windows 10 but using Windows Subsystem for Linux (Ubuntu 18.04 specifically) and can strongly recommend that approach. Alternatively, if you have Docker for Windows installed then you might want to try out https://github.com/zalando/zally/pull/917, although I haven't got round to testing it yet.

**Comment by vivanov19** [comment]
Hi Rob,

First of all, Rob thank you very much for the rapid and detailed reply.

With regards running Zally natively on Windows 10 as you suspected your direction is a starting point, but not a full solution. It is mounting UI on the port 3000 and still stalls:

C:\Enterprise2019\zally-master\web-ui>node_modules\.bin\nodemon.cmd server.js
[nodemon] 1.12.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Enterprise2019\zally-master\web-ui\src\server/**/* ./server.**/*
[nodemon] starting `node server.js`
zally-web-ui mounted on "/"
zally-web-ui running at http://localhost:3000

Therefore, I've tried the #917 suggestion (one big image with all artifacts as discussed in the #917 ticket). The reason I've picked up it vs. your routine approach with Linux / Ubuntu (on Windows on elsewhere I believe) is our company approach to use containers (Docker & k8s) as much as possible. So, it seems I've successfully created the image (Linux Docker container on Windows), push it the Docker hub and even run it on Windows 10. There are definitely some severe warnings in the logging. Please see two attached DOS shell outputs: image creation and Linux image run on Windows. Assuming (from the code analysis) that the front-end call is just http://localhost:8080/ I still have no Zally UI running on it.

It seems the last resort is to "run Zally under Windows 10 but using Windows Subsystem for Linux (Ubuntu 18.04 specifically) and can strongly recommend that approach". Would you please elaborate a bit on the approach. I am out of the city / business for a week starting tomorrow, but really appreciate any further comments on the topics and will explore them on my return.

Thank you very much in advance.

Thanks,
VLADIMIR IVANOV, PhD
Principal Architect, Integration
Advanced Research, Patterns and Practices, and Innovation

[FINASTRA]

Finastra 55 Standish Court, Floor 3, Mississauga, Ontario, L5R 4A1, Canada
D: +00 (1)905 267 5000 | M: +00 (1)647 6259 336 | E: vladimir.ivanov@finastra.com<mailto:vladimir.ivanov@finastra.com>
Finastra.com<http://www.finastra.com/>


"FINASTRA" is the trade name of the FINASTRA group of companies. This email and any attachments have been scanned for known viruses using multiple scanners. This email message is intended for the named recipient only. It may be privileged and/or confidential. If you are not the named recipient of this email please notify us immediately and do not copy it or use it for any purpose, nor disclose its contents to any other person. This email does not constitute the commencement of legal relations between you and FINASTRA. Please refer to the executed contract between you and the relevant member of the FINASTRA group for the identity of the contracting party with which you are dealing.

**Comment by vivanov19** [comment]
First of all, Rob thank you very much for the rapid and detailed reply.

With regards running Zally natively on Windows 10 as you suspected your direction is a starting point, but not a full solution. It is mounting UI on the port 3000 and still stalls:
C:\Enterprise2019\zally-master\web-ui>node_modules\.bin\nodemon.cmd server.js
[nodemon] 1.12.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\Enterprise2019\zally-master\web-ui\src\server/**/* ./server.**/*
[nodemon] starting `node server.js`
zally-web-ui mounted on "/"
zally-web-ui running at http://localhost:3000

Therefore, I've tried the #917 suggestion (one big image with all artifacts as discussed in the #917 ticket). The reason I've picked up it vs. your routine approach with Linux / Ubuntu (on Windows on elsewhere I believe) is our company approach to use containers (Docker & k8s) as much as possible. So, it seems I've successfully created the image (Linux Docker container on Windows), push it the Docker hub and even run it on Windows 10. There are definitely some severe warnings in the logging. Please see two attached DOS shell outputs: image creation and Linux image run on Windows. Assuming (from the code analysis) that the front-end call is just http://localhost:8080/ I still have no Zally UI running on it.

It seems the last resort is to "run Zally under Windows 10 but using Windows Subsystem for Linux (Ubuntu 18.04 specifically) and can strongly recommend that approach". Would you please elaborate a bit on the approach. I am out of the city / business for a week starting tomorrow, but really appreciate any further comments on the topics and will explore them on my return.

Thank you very much in advance

**Comment by maxim-tschumak** [comment]
@vivanov19 Did it work out for you?

**Comment by vivanov19** [comment]
Sorry for the delay with the reply; I had a few business trips. I've rebuild both paths from scratch and this is where I am staying (Windows 10).
1. Follow Rob's recommendation for UI module I can start it:
C:\Enterprise2019\zally-master\web-ui>node_modules.bin\nodemon.cmd server.js
[nodemon] 1.12.7
[nodemon] to restart at any time, enter rs
[nodemon] watching: C:\Enterprise2019\zally-master\web-ui\src\server//* ./server./*
[nodemon] starting node server.js
zally-web-ui mounted on "/"
zally-web-ui running at http://localhost:3000
.... and even get "Zally API Linter WEB UI" label and image in my browser, but with blank, empty page. It looks UI service running in some extend.

2. Container approach follow #917 (Docker again is running on Windows 10). On Windows 10 I can run both Linux and Windows containers. For Linux mode:
2a. I can successfully create and run image:
Step 14/14 : CMD ["node", "server.js"]
 ---> Using cache
 ---> 3f41c4bbb0a9
Successfully built 3f41c4bbb0a9
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

C:\Enterprise2019\zally-master\web-ui>docker run -it 3f41c4bbb0a9
zally-web-ui mounted on "/"
zally-web-ui running at http://localhost:3000

I can't invoke anything on port 3000 probably because of this warning. I made sure I have only one container running on port 3000:

2b. When I switched to the Docker Windows container I just failed to create an image:

Sending build context to Docker daemon  249.7MB
Step 1/14 : FROM registry.opensource.zalan.do/stups/node:8.8.0-alpine-33 as yarn-image
8.8.0-alpine-33: Pulling from stups/node
image operating system "linux" cannot be used on this platform

3. Rob suggested to "run Zally under Windows 10 but using Windows Subsystem for Linux (Ubuntu 18.04 specifically) and can strongly recommend that approach". I am not sure what exactly should be done to do this.

As I said, at the begging the backend server is running and we can successfully Utilize the "zally --linter-service "http://localhost:8000" --format pretty lint *.yaml", but to have UI running is definitely the ultimate goal to make the framework as the company standard.

Any help would be highly appreciated.
Thank you very much,
Vlad

**Comment by maxim-tschumak** [comment]
I don't have experience running Zally under Windows (and also don't have a Windows machine to reproduce).

But maybe I can bring you one step further: Do `docker run -it -p 3000:3000 3f41c4bbb0a9` instead of `docker run -it 3f41c4bbb0a9` to start Zally Web UI Docker container. It publishes containers internal port (`3000`) to the host (maps to `3000`).

**Comment by roxspring** [comment]
These are tested notes based on my setup, happy to move them into a markdown document in the project if that helps...

# Building Under Windows Subsystem for Linux

The following notes document my working environment for building and testing a full Zally installation from a Windows 10 workstation.

## Prepare Windows Environment

- Download and install Docker for Windows

  - https://hub.docker.com/editions/community/docker-ce-desktop-windows

- Open Microsoft Store

  - Search for linux

  - Install Debian (or Ubuntu, other linuxes may need different commands for package management)

  - Launch the Debian console

## Prepare Linux Environment

- In the Debian console:

  - enter a username & password to complete the installation

- Install some general prerequisites

  ```bash
  sudo apt-get update -y && sudo apt-get install -y git openjdk-8-jdk curl make g++
  ```

  (I was quite surprised to see that `make` and `g++` were necessary to build some dependency of the web-ui)

- Install NodeJS

  - https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions

  ```bash
  curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  sudo apt-get install -y nodejs
  ```

- Make Windows docker binaries available on linux path:

  ```bash
  sudo ln -s /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker.exe /usr/local/bin/docker
  sudo ln -s /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-compose.exe /usr/local/bin/docker-compose
  sudo ln -s /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-machine.exe /usr/local/bin/docker-machine
  sudo ln -s /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-credential-wincred.exe /usr/local/bin/docker-credential-wincred
  ```

- Clone Zally into a folder easily addressable under Windows (C:\Zally)

  ```bash
  cd /mnt/c
  git clone https://github.com/zalando/zally
  cd zally

## Build and Run

Run the following script to build and then run the services under docker:

```bash
./build-and-run.sh
```

It'll take a while but eventually you'll see something like the following to indicate that we're ready to connect:

```
Started ApplicationKt in 36.576 seconds (JVM running for 40.144)
```

## Testing

Use a browser to check that things are working correctly:

- <http://localhost:8000/supported-rules> - should have a JSON response including a list of rules
- <http://localhost:8080/> - should show the UI including Zally icon top left
- <http://localhost:8080/rules?is_active=true> - should show a list presenting a subset of the rules above

## Troubleshooting

Variations on the following error messages are a regular occurrence when building the web-ui under Windows. The command in question can typically be rerun without producing exactly the same occurrence, so incrementally the command gets further each run. (Producing this guide took 5x attempts at the web-ui build before a full run completed).

```
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/home/username/.cache/yarn/v1/npm-react-ace-5.8.0-872d9ee8b664300ed5ab9edac6234bbe90836836/webpack.config.base.js' -> '/mnt/c/zally/web-ui/node_modules/react-ace/webpack.config.base.js'".
```

**Comment by maxim-tschumak** [comment]
Let's add this page to the docs.

**Comment by roxspring** [comment]
A few further thoughts that occurred to me while checking the WSL notes above:

1. `build-and-run.sh` forces a full "clean" rebuild of the server. Is there any reason for this? The fact that a clean build has to rerun _all_ tests combined with the fact that the initial yarn build often fails the first 4 runs makes this particularly painful.

2. I wonder if we're confusing matters by having the web-ui talk about port 3000 but then map 8080 -> 3000 during docker-compose.

3. @vivanov19 in addition to @maxim-tschumak's point above, have you confirmed that you have no other servers running on port 3000 or 8080?

**Comment by maxim-tschumak** [comment]
> 1. `build-and-run.sh` forces a full "clean" rebuild of the server. Is there any reason for this?

Not really, I always prefer a clean build. We can exclude the tests to speed up the process.

**Comment by roxspring** [comment]
> Not really, I always prefer a clean build. We can exclude the tests to speed up the process.

Opened #933 to do incremental build - suggest any further discussion happens there and this issue can remain Windows focused.

**Comment by vivanov19** [comment]
Thank you very much, Rob and Maxim. It is much better understanding now how the framework's components should be integrated.

1. Yes, there is no server running on 3000 and all services on 8080 stopped.
2. I will try both options: Docker on Windows with important clarifications above and new for me Linux on Windows, and let you know. It is not a bad idea to have Linux running on Windows no matter what :-)

Thank you very much for the extremely helpful comments.

**Comment by vadeg** [comment]
No additional actions are required.
