### ISSUE TITLE
Zally local setup - WEB UI not rendering

### ISSUE THREAD

**Issue by avaradan** [zalando/zally#938]
Hi, I am having same issue in web UI rendering. I setup the project recently and ran ./build-and-run.sh but UI shows nothing. Can someone pls help me?

![image](https://user-images.githubusercontent.com/8282477/54103979-5fcf1980-43f4-11e9-8f98-16ecd1619fa0.png)

Attaching the startup log below.
[zally.log](https://github.com/zalando/zally/files/2950872/zally.log)

wget command has no issues.
aravindanvaradan@Arvindan3150161:~/zally/zally-master/web-ui$ wget localhost:8080
--2019-03-11 11:40:35-- http://localhost:8080/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1548 (1.5K) [text/html]
Saving to: ‘index.html’

index.html 100%[=================================================>] 1.51K --.-KB/s in 0s

2019-03-11 11:40:35 (155 MB/s) - ‘index.html’ saved [1548/1548]

**Comment by avaradan** [comment]
Apparently it is the issue with yarn. It was not installed properly. After reinstalling, UI is rendering properly.

**Comment by bksun** [comment]
@avaradan are you able to click on "Edit" button beside "validate" button ?
 I'm facing cors error.

**Comment by avaradan** [comment]
Sorry I am not using this anymore. Did not check this.

-Aravind

**Comment by bksun** [comment]
Thanks a lot for reply.
