### ISSUE TITLE
"S007: Define maximum length for string properties" should be skipped if format was specified

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/zally#956]
Specifying a format like `date-time` should suppress this violation.

**Comment by roxspring** [comment]
Yeah, had wondered about that but it's clearly not that simple. `date` and `date-time` formats both have effective string length limits built in, but `password`, `byte`, `binary` don't imply any limit. Implementations support additional formats, some of which imply a limit `uuid`, `ipv4`, `ipv6`, and some that don't `email`, `uri`, `hostname`. How about adding something to rules config whitelisting the patterns which imply a limit:

```
StringPropertyLenghtBoundsRule {
  format_whitelist: [ date, date-time, uuid, ipv4, ipv6 ]
}
```

Similarly `pattern` defines a regex that strings need to meet, which may or may not imply a limit. I guess we could attempt to parse the regex and check for unbounded quantifiers to figure out which patterns are limited, but I suspect this isn't easy to get right. Perhaps following from above we could also make that configurable too:

```
StringPropertyLenghtBoundsRule {
  pattern_implies_limit: true
}
```
