### ISSUE TITLE
Extract validator to separate module

### ISSUE THREAD

**Issue by RoyJacobs** [zalando/zally#963]
Hi, I'm currently working on an [API Registry](https://github.com/bolcom/katalog) for which I'd love to add Swagger+OpenAPI validation. To make it easier to manage rulesets I would like to be able to use the Zally validator as a separate module without any of the dependencies it currently includes (things like Spring Boot, Flyway, Undertow, etc).

Do you see the validator as something that could be extracted, or do you consider it in an inextricable part of the server?

**Comment by maxim-tschumak** [comment]
This is a very valid point. So far we didn't go in this direction because we didn't have such use cases.

I think we should finish the [Rule Set epic](https://github.com/zalando/zally/issues/551) and then we can think about how to extract Zally lib out of the Zally server.

**Comment by RoyJacobs** [comment]
Great, I'll keep my eyes peeled.
